"""Shared settings for the Map data pipeline."""

from __future__ import annotations

from pathlib import Path

from knowledge_base.publishing.generated_assets import MAP_DATA, MAP_SIMILARITY

MAP_DIR = Path(__file__).resolve().parents[1]
KB_DIR = MAP_DIR.parents[1]
REPO_ROOT = KB_DIR.parent
DOCS_DIR = KB_DIR / "docs"
METADATA_ROOT = DOCS_DIR / "papers"
SITE_CONFIG = KB_DIR / "zensical.yml"
CACHE_DIR = MAP_DIR / "cache"
GENERATED_DIR = MAP_DIR / "generated"
BROWSER_DIR = MAP_DIR / "browser"
VENDOR_DIR = MAP_DIR / "vendor"

DEFAULT_CACHE = CACHE_DIR / "embedding_cache.json"
DEFAULT_OUTPUT = GENERATED_DIR / MAP_DATA.name
DEFAULT_SIMILARITY_OUTPUT = GENERATED_DIR / MAP_SIMILARITY.name
DEFAULT_FASTEMBED_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
DEFAULT_SHARED_CHUNK_CACHE = KB_DIR / "components" / "semantic_search" / "embedding_cache.json"

DEFAULT_UMAP_SCALE = 1500.0
SIMILARITY_EXPORT_SCALE = 1000
EMBED_PROGRESS_INTERVAL = 32
TREE_PROXIMITY_HISTOGRAM_BINS = 101
MAP_DATA_FORMAT_VERSION = 2
INCREMENTAL_LAYOUT_MAX_ADDED = 50
INCREMENTAL_LAYOUT_MAX_ADDED_RATIO = 0.05
INCREMENTAL_LAYOUT_NEIGHBORS = 8
INCREMENTAL_LAYOUT_JITTER_RATIO = 0.35

UNCATEGORIZED_CATEGORY = "Uncategorized"
LEGACY_BRANCH_LEVEL_IDS = ["super_category", "category", "sub_category"]
NODE_DIAMETER_SCALE = 2
PAPER_NODE_RADIUS_TARGET = 12 * NODE_DIAMETER_SCALE
AGGREGATE_EXTRA_AREA_UNITS_BY_LEVEL = [18, 12, 8, 5, 3]
AGGREGATE_EXTRA_AREA_FALLBACK_UNITS = 2
AGGREGATE_MIN_RADIUS_RATIO = 1.7
AGGREGATE_POSITION_OUTER_QUANTILE = 0.84
AGGREGATE_POSITION_BIAS_BY_LEVEL = [0.68, 0.52, 0.36, 0.24]
AGGREGATE_COLLISION_PADDING = 0.75
AGGREGATE_FINAL_COLLISION_ITERATIONS = 240
AGGREGATE_COLLISION_EPSILON = 1e-3
