"""Constants for staged arXiv metadata refinement."""

from __future__ import annotations

import re
from pathlib import Path

CACHE_PATH = Path("/tmp/kb_refine_staged_arxiv_metadata_cache.json")
ARXIV_URL_RE = re.compile(r"(?:arxiv\.org|ar5iv\.labs\.arxiv\.org)", re.IGNORECASE)
ARXIV_DOI_RE = re.compile(r"10\.48550/arxiv", re.IGNORECASE)

PHRASE_TAGS: tuple[tuple[str, str], ...] = (
    ("affine rank minimization", "Affine rank minimization"),
    ("rank minimization", "Rank minimization"),
    ("minimum rank", "Minimum rank"),
    ("low-rank", "Low-rank models"),
    ("low rank", "Low-rank models"),
    ("matrix completion", "Matrix completion"),
    ("matrix factorization", "Matrix factorization"),
    ("linear matrix equation", "Linear matrix equations"),
    ("nuclear norm", "Nuclear norm minimization"),
    ("restricted isometry", "Restricted isometry property"),
    ("compressed sensing", "Compressed sensing"),
    ("convex optimization", "Convex optimization"),
    ("convex relaxation", "Convex relaxation"),
    ("semidefinite", "Semidefinite programming"),
    ("linear programming", "Linear programming"),
    ("integer programming", "Integer programming"),
    ("nonconvex", "Nonconvex optimization"),
    ("stochastic optimization", "Stochastic optimization"),
    ("gradient descent", "Gradient descent"),
    ("stochastic gradient", "Stochastic gradients"),
    ("natural gradient", "Natural gradients"),
    ("mirror descent", "Mirror descent"),
    ("policy gradient", "Policy gradients"),
    ("reinforcement learning", "Reinforcement learning"),
    ("inverse reinforcement learning", "Inverse reinforcement learning"),
    ("imitation learning", "Imitation learning"),
    ("q-learning", "Q-learning"),
    ("markov decision process", "Markov decision processes"),
    ("partially observable", "Partial observability"),
    ("bellman", "Bellman equations"),
    ("policy iteration", "Policy iteration"),
    ("value iteration", "Value iteration"),
    ("multi-agent", "Multi-agent systems"),
    ("multiagent", "Multi-agent systems"),
    ("game theory", "Game theory"),
    ("bandit", "Bandits"),
    ("regret", "Regret bounds"),
    ("optimal control", "Optimal control"),
    ("model predictive control", "Model predictive control"),
    ("predictive control", "Predictive control"),
    ("trajectory optimization", "Trajectory optimization"),
    ("motion planning", "Motion planning"),
    ("path planning", "Path planning"),
    ("robot", "Robotics"),
    ("quadrotor", "Aerial robotics"),
    ("autonomous driving", "Autonomous driving"),
    ("vehicle", "Vehicles"),
    ("control barrier", "Control barrier functions"),
    ("control lyapunov", "Control Lyapunov functions"),
    ("lyapunov", "Lyapunov methods"),
    ("stability", "Stability analysis"),
    ("safe", "Safety"),
    ("safety", "Safety"),
    ("robust", "Robustness"),
    ("uncertainty", "Uncertainty"),
    ("gaussian process", "Gaussian processes"),
    ("kalman", "Kalman filtering"),
    ("system identification", "System identification"),
    ("state estimation", "State estimation"),
    ("neural network", "Neural networks"),
    ("deep learning", "Deep learning"),
    ("convolutional", "Convolutional networks"),
    ("recurrent neural", "Recurrent neural networks"),
    ("transformer", "Transformers"),
    ("attention", "Attention mechanisms"),
    ("graph neural", "Graph neural networks"),
    ("graph convolution", "Graph neural networks"),
    ("diffusion model", "Diffusion models"),
    ("diffusion", "Diffusion models"),
    ("generative adversarial", "Generative adversarial networks"),
    ("variational autoencoder", "Variational autoencoders"),
    ("autoencoder", "Autoencoders"),
    ("large language model", "Large language models"),
    ("language model", "Language models"),
    ("foundation model", "Foundation models"),
    ("vision-language", "Vision-language models"),
    ("vision language", "Vision-language models"),
    ("image generation", "Image generation"),
    ("computer vision", "Computer vision"),
    ("object detection", "Object detection"),
    ("semantic segmentation", "Semantic segmentation"),
    ("image segmentation", "Image segmentation"),
    ("pose estimation", "Pose estimation"),
    ("optical flow", "Optical flow"),
    ("representation learning", "Representation learning"),
    ("self-supervised", "Self-supervised learning"),
    ("semi-supervised", "Semi-supervised learning"),
    ("supervised learning", "Supervised learning"),
    ("unsupervised learning", "Unsupervised learning"),
    ("federated learning", "Federated learning"),
    ("meta-learning", "Meta-learning"),
    ("few-shot", "Few-shot learning"),
    ("transfer learning", "Transfer learning"),
    ("bayesian", "Bayesian methods"),
    ("probabilistic", "Probabilistic models"),
    ("causal", "Causal inference"),
    ("graph", "Graphs"),
    ("nearest neighbor", "Nearest neighbors"),
    ("clustering", "Clustering"),
    ("classification", "Classification"),
    ("regression", "Regression"),
    ("time series classification", "Time series classification"),
    ("time series", "Time series"),
    ("computational complexity", "Computational complexity"),
    ("convolutional kernel", "Convolutional kernels"),
    ("linear classifier", "Linear classifiers"),
    ("deterministic transform", "Deterministic transforms"),
    ("state-of-the-art", "State of the art"),
    ("ucr archive", "UCR archive"),
    ("classifier", "Classifiers"),
    ("dataset", "Datasets"),
    ("benchmark", "Benchmarks"),
    ("accuracy", "Accuracy"),
    ("scalability", "Scalability"),
    ("real-time", "Real-time systems"),
    ("online", "Online algorithms"),
    ("offline", "Offline algorithms"),
    ("sampling-based", "Sampling-based methods"),
    ("sampling based", "Sampling-based methods"),
    ("search tree", "Search trees"),
    ("nearest-neighbor", "Nearest neighbors"),
    ("collaborative filtering", "Collaborative filtering"),
    ("euclidean embedding", "Euclidean embedding"),
    ("information retrieval", "Information retrieval"),
    ("ranking", "Ranking"),
    ("privacy", "Privacy"),
    ("differential privacy", "Differential privacy"),
    ("security", "Security"),
    ("cryptograph", "Cryptography"),
    ("distributed", "Distributed systems"),
    ("parallel computing", "Parallel computing"),
    ("linear equality constraint", "Linear equality constraints"),
    ("minimum-rank solution", "Minimum-rank solutions"),
    ("linear transformation", "Linear transformations"),
    ("cardinality minimization", "Cardinality minimization"),
    ("random ensemble", "Random ensembles"),
    ("np-hard", "NP-hardness"),
    ("sample complexity", "Sample complexity"),
    ("generalization", "Generalization"),
    ("out-of-distribution", "Out-of-distribution generalization"),
    ("optimization", "Optimization"),
    ("planning", "Planning"),
    ("control", "Control"),
    ("learning", "Learning"),
    ("sampling", "Sampling"),
    ("monte carlo", "Monte Carlo methods"),
    ("variational inference", "Variational inference"),
    ("normalizing flow", "Normalizing flows"),
    ("optimal transport", "Optimal transport"),
    ("wasserstein", "Wasserstein distances"),
)

TAG_STOPWORDS = {
    "a",
    "an",
    "and",
    "as",
    "by",
    "for",
    "from",
    "in",
    "into",
    "of",
    "on",
    "or",
    "the",
    "to",
    "via",
    "with",
    "without",
}

GENERIC_OPENALEX_TAGS = {
    "algorithm",
    "algorithms",
    "artificial intelligence",
    "computer science",
    "engineering",
    "mathematics",
    "method",
    "methods",
    "physics",
}

SENTENCE_LIKE_TAG_START_RE = re.compile(
    r"^(?:"
    r"we\b|"
    r"i\b|"
    r"our\b|"
    r"this\s+(?:paper|work|article|study)\b|"
    r"the\s+(?:paper|work|article|study|authors?)\b|"
    r"in\s+this\s+(?:paper|work|article|study)\b"
    r")",
    re.IGNORECASE,
)
SENTENCE_LIKE_TAG_CLAUSE_RE = re.compile(
    r"\b(?:argue|argues|show|shows|prove|proves|demonstrate|demonstrates|"
    r"present|presents|propose|proposes|introduce|introduces|study|studies|"
    r"investigate|investigates|claim|claims)\s+that\b",
    re.IGNORECASE,
)
