"""Tag audit constants and regexes."""

import re

from knowledge_base.config import KB_DIR

_URL_RE = re.compile(r"\b(?:https?://|ftp://|www\.)[^\s<>()]+", re.IGNORECASE)
_SENTENCE_LIKE_TAG_START_RE = re.compile(
    r"^(?:"
    r"we\b|"
    r"i\b|"
    r"our\b|"
    r"this\s+(?:paper|work|article|study)\b|"
    r"the\s+(?:paper|work|article|study|authors?)\b|"
    r"in\s+this\s+(?:paper|work|article|study)\b"
    r")",
    re.IGNORECASE,
)
_SENTENCE_LIKE_TAG_CLAUSE_RE = re.compile(
    r"\b(?:argue|argues|show|shows|prove|proves|demonstrate|demonstrates|"
    r"present|presents|propose|proposes|introduce|introduces|study|studies|"
    r"investigate|investigates|claim|claims)\s+that\b",
    re.IGNORECASE,
)
_COMMON_SHORT_TAG_WORDS = {
    "agent",
    "agents",
    "bandit",
    "code",
    "color",
    "cost",
    "data",
    "deep",
    "edge",
    "end",
    "few",
    "filter",
    "game",
    "graph",
    "high",
    "in",
    "image",
    "lane",
    "long",
    "loop",
    "low",
    "map",
    "maps",
    "model",
    "motion",
    "of",
    "off",
    "on",
    "one",
    "open",
    "out",
    "path",
    "policy",
    "pose",
    "real",
    "risk",
    "robot",
    "robots",
    "safe",
    "safety",
    "scene",
    "search",
    "short",
    "shot",
    "state",
    "states",
    "time",
    "to",
    "tree",
    "trees",
    "value",
    "values",
    "vision",
    "zero",
}
_TAG_LEADING_ARTICLES = {"a", "an", "and", "as", "i", "in", "or", "recent", "such", "the", "we"}
_MAX_TAG_WORDS = 4
_PLURAL_DUPLICATE_TAG_MESSAGE_PREFIX = "Duplicate tag value(s) after trivial plural normalization"
_DUPLICATE_TAG_MESSAGE_PREFIX = "Duplicate tag value(s)"
_DATABASE_DUPLICATE_TAG_MESSAGE_PREFIX = "Duplicate tag value(s) after tag database normalization"
_TAG_DATABASE_ISSUE_PREFIX = "Tag differs from normalization database"
_TAG_DATABASE_MISSING_ISSUE_PREFIX = "Tag is missing from normalization database"
_FORBIDDEN_TAGS = {
    "state of the art": "too generic to be useful as a tag",
}
_LONG_TAG_ALLOWLIST = {
    "alternating-direction method of multipliers",
    "covariance matrix adaptation evolution strategy",
    "distributionally robust model predictive path integral control",
    "global positioning system-denied navigation",
    "graph-based simultaneous localization and mapping",
    "greedy randomized adaptive search procedure",
    "informed rapidly-exploring random tree star",
    "joint photographic experts group 2000",
    "law of the iterated logarithm",
    "metric-semantic simultaneous localization and mapping",
    "model predictive path integral belief",
    "model predictive path integral control",
    "partially observable markov decision process",
    "predictive-action model predictive path integral control",
    "sliding-window informed rapidly-exploring random tree star",
    "structural similarity index measure",
    "trust region policy optimization",
    "worst-case conditional value at risk",
}
_TAGS_DB = KB_DIR / "normalization" / "tags.yml"
_TAGS_DB_HEADER = """# Tag normalization database.
# Canonical tags should use full spelling instead of acronyms. Add observed
# variants, abbreviations, plural/singular forms, and casing variants under aliases.
# Generated by scripts/build_normalization_db.py; edit by hand as needed."""
_NON_PLURAL_S_ENDINGS = ("ss", "us", "is", "ics")
_NON_PLURAL_S_WORDS = {
    "bias",
    "canvas",
    "chaos",
    "cosmos",
    "kinematics",
    "mathematics",
    "physics",
    "robotics",
    "semantics",
    "statistics",
}
_TAG_PROPER_NAME_WORDS = {
    "aitken": "Aitken",
    "arnoldi": "Arnoldi",
    "bayes": "Bayes",
    "bayesian": "Bayesian",
    "bellman": "Bellman",
    "broyden": "Broyden",
    "carlo": "Carlo",
    "chebyshev": "Chebyshev",
    "delaunay": "Delaunay",
    "dijkstra": "Dijkstra",
    "euclidean": "Euclidean",
    "euler": "Euler",
    "floyd": "Floyd",
    "ford": "Ford",
    "frank": "Frank",
    "franka": "Franka",
    "gauss": "Gauss",
    "gaussian": "Gaussian",
    "hamilton": "Hamilton",
    "hamiltonian": "Hamiltonian",
    "jacobi": "Jacobi",
    "kalman": "Kalman",
    "krylov": "Krylov",
    "kutta": "Kutta",
    "lagrange": "Lagrange",
    "lagrangian": "Lagrangian",
    "laplace": "Laplace",
    "levenberg": "Levenberg",
    "levy": "Levy",
    "liapunov": "Liapunov",
    "lyapunov": "Lyapunov",
    "markov": "Markov",
    "markovian": "Markovian",
    "marquardt": "Marquardt",
    "monte": "Monte",
    "newton": "Newton",
    "newtonian": "Newtonian",
    "pontryagin": "Pontryagin",
    "riccati": "Riccati",
    "runge": "Runge",
    "schur": "Schur",
    "warshall": "Warshall",
    "wolfe": "Wolfe",
}

__all__ = [name for name in globals() if name.startswith("_") and not name.startswith("__")]
