"""Build starter author/source normalization databases from metadata.yml files.

Usage:
  python scripts/build_normalization_db.py
  python scripts/build_normalization_db.py --update
  python scripts/build_normalization_db.py --force
  python scripts/build_normalization_db.py --dry-run

The generated databases are intended to be manually curated over time. They
store canonical names plus aliases that audit_normalization.py can use for
suggestions and safe fixes.
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

import yaml


REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from knowledge_base.config import KB_DIR  # noqa: E402
from knowledge_base.utils.normalization_db import (  # noqa: E402
    ascii_clean,
    author_initial_last_key,
    author_key,
    canonical_author_display,
    canonical_source_display,
    dump_yaml,
    entry_aliases,
    load_yaml,
    parse_author,
    source_key,
)


METADATA_ROOT = KB_DIR / "docs" / "papers"
NORMALIZATION_DIR = KB_DIR / "normalization"
AUTHORS_DB = NORMALIZATION_DIR / "authors.yml"
SOURCES_DB = NORMALIZATION_DIR / "sources.yml"

AUTHORS_HEADER = """# Author normalization database.
# Canonical author names should use ASCII, full first name, middle initial(s)
# when known, and full last name. Add observed variants under aliases.
# Generated by scripts/build_normalization_db.py; edit by hand as needed."""

SOURCES_HEADER = """# Source/venue normalization database.
# Canonical sources should use the preferred venue name without publication
# years. Add abbreviations or alternate spellings under aliases.
# Generated by scripts/build_normalization_db.py; edit by hand as needed."""


def as_list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else []


def load_metadata(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    return data if isinstance(data, dict) else {}


def collect_values(metadata_root: Path) -> tuple[Counter[str], Counter[str]]:
    authors: Counter[str] = Counter()
    sources: Counter[str] = Counter()
    for metadata_path in sorted(metadata_root.rglob("metadata.yml")):
        data = load_metadata(metadata_path)
        for author in as_list(data.get("authors")):
            author_text = str(author).strip()
            if author_text:
                authors[author_text] += 1

        source = str(data.get("source") or "").strip()
        if source:
            sources[source] += 1
    return authors, sources


def existing_entries(path: Path, field: str) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    entries = load_yaml(path).get(field)
    return [entry for entry in entries if isinstance(entry, dict)] if isinstance(entries, list) else []


def author_quality(name: str, count: int) -> tuple[int, int, int, int, str]:
    parsed = parse_author(name)
    if parsed is None:
        return (0, 0, 0, count, name)
    no_edge_initials = int(not parsed.first_is_initial and not parsed.last_is_initial)
    ascii_only = int(ascii_clean(name) == name)
    middle_initials = sum(1 for part in parsed.middle if len(part.rstrip(".")) == 1)
    return (no_edge_initials, ascii_only, middle_initials, count, name)


def choose_author_canonical(names: list[str], counts: Counter[str]) -> str:
    best = max(names, key=lambda name: author_quality(name, counts[name]))
    return canonical_author_display(best)


def merge_aliases(canonical: str, values: list[str]) -> list[str]:
    aliases = {
        ascii_clean(value)
        for value in values
        if ascii_clean(value) and ascii_clean(value) != canonical
    }
    return sorted(aliases, key=str.casefold)


def build_author_entries(
    values: Counter[str],
    *,
    existing: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    canonical_to_values: dict[str, set[str]] = defaultdict(set)
    key_to_existing: dict[str, str] = {}
    for entry in existing:
        canonical = str(entry.get("canonical") or "").strip()
        if not canonical:
            continue
        canonical_to_values[canonical].add(canonical)
        for alias in entry_aliases(entry):
            canonical_to_values[canonical].add(alias)
        for value in canonical_to_values[canonical]:
            key_to_existing[author_key(value)] = canonical

    unmatched: dict[str, list[str]] = defaultdict(list)
    for value in values:
        key = author_key(value)
        canonical = key_to_existing.get(key)
        if canonical:
            canonical_to_values[canonical].add(value)
        else:
            unmatched[key].append(value)

    parsed_by_initial: dict[str, list[str]] = defaultdict(list)
    for names in unmatched.values():
        for name in names:
            key = author_initial_last_key(name)
            if key:
                parsed_by_initial[key].append(name)

    assigned: set[str] = set()
    for initial_key, names in parsed_by_initial.items():
        parsed_names = [(name, parse_author(name)) for name in names]
        full_first_names = {
            parsed.first.casefold()
            for _, parsed in parsed_names
            if parsed is not None and not parsed.first_is_initial and not parsed.last_is_initial
        }
        if len(full_first_names) != 1:
            continue
        canonical = choose_author_canonical(names, values)
        canonical_to_values[canonical].update(names)
        assigned.update(names)

    for names in unmatched.values():
        remaining = [name for name in names if name not in assigned]
        if not remaining:
            continue
        canonical = choose_author_canonical(remaining, values)
        canonical_to_values[canonical].update(remaining)

    entries = []
    for canonical in sorted(canonical_to_values, key=str.casefold):
        aliases = merge_aliases(canonical, sorted(canonical_to_values[canonical]))
        entry: dict[str, Any] = {"canonical": canonical}
        if aliases:
            entry["aliases"] = aliases
        entries.append(entry)
    return entries


def build_source_entries(
    values: Counter[str],
    *,
    existing: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    canonical_to_values: dict[str, set[str]] = defaultdict(set)
    key_to_existing: dict[str, str] = {}
    for entry in existing:
        canonical = str(entry.get("canonical") or "").strip()
        if not canonical:
            continue
        canonical_to_values[canonical].add(canonical)
        for alias in entry_aliases(entry):
            canonical_to_values[canonical].add(alias)
        for value in canonical_to_values[canonical]:
            key_to_existing[source_key(value)] = canonical

    unmatched: dict[str, list[str]] = defaultdict(list)
    for value in values:
        key = source_key(value)
        canonical = key_to_existing.get(key)
        if canonical:
            canonical_to_values[canonical].add(value)
        else:
            unmatched[key].append(value)

    for names in unmatched.values():
        best = max(names, key=lambda name: (values[name], len(name), name))
        canonical = canonical_source_display(best)
        canonical_to_values[canonical].update(names)

    entries = []
    for canonical in sorted(canonical_to_values, key=str.casefold):
        aliases = merge_aliases(canonical, sorted(canonical_to_values[canonical]))
        entry: dict[str, Any] = {"canonical": canonical}
        if aliases:
            entry["aliases"] = aliases
        entries.append(entry)
    return entries


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build starter author/source normalization databases."
    )
    parser.add_argument(
        "--update",
        action="store_true",
        help="Merge newly observed names/sources into existing databases.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Rebuild databases from scratch even if they already exist.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print counts without writing database files.",
    )
    args = parser.parse_args()

    if args.update and args.force:
        parser.error("--update and --force are mutually exclusive")

    if (
        not args.update
        and not args.force
        and (AUTHORS_DB.exists() or SOURCES_DB.exists())
        and not args.dry_run
    ):
        print(
            "Normalization databases already exist. Use --update to merge new values or --force to rebuild.",
            file=sys.stderr,
        )
        return 2

    authors, sources = collect_values(METADATA_ROOT)
    author_entries = build_author_entries(
        authors,
        existing=existing_entries(AUTHORS_DB, "authors") if args.update else [],
    )
    source_entries = build_source_entries(
        sources,
        existing=existing_entries(SOURCES_DB, "sources") if args.update else [],
    )

    print(
        f"Observed {len(authors)} author spellings -> {len(author_entries)} author entries."
    )
    print(
        f"Observed {len(sources)} source spellings -> {len(source_entries)} source entries."
    )

    if args.dry_run:
        return 0

    dump_yaml(AUTHORS_DB, {"version": 1, "authors": author_entries}, header=AUTHORS_HEADER)
    dump_yaml(SOURCES_DB, {"version": 1, "sources": source_entries}, header=SOURCES_HEADER)
    print(f"Wrote {AUTHORS_DB.relative_to(KB_DIR)}")
    print(f"Wrote {SOURCES_DB.relative_to(KB_DIR)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
