"""Build starter author/source/tag normalization databases from metadata.yml files.

Usage:
  python scripts/build_normalization_db.py
  python scripts/build_normalization_db.py --update
  python scripts/build_normalization_db.py --force
  python scripts/build_normalization_db.py --dry-run

The generated databases are intended to be manually curated over time. They
store canonical names/tags plus aliases that audit_normalization.py can use for
suggestions and safe fixes.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

import yaml


REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from knowledge_base.config import KB_DIR  # noqa: E402
from knowledge_base.utils.normalization_db import (  # noqa: E402
    ascii_clean,
    author_initial_last_key,
    author_key,
    canonical_author_display,
    canonical_source_display,
    dump_yaml,
    entry_aliases,
    expand_tag_acronyms,
    load_yaml,
    parse_author,
    source_key,
    tag_dedupe_key,
    tag_key,
)


METADATA_ROOT = KB_DIR / "docs" / "papers"
NORMALIZATION_DIR = KB_DIR / "normalization"
AUTHORS_DB = NORMALIZATION_DIR / "authors.yml"
SOURCES_DB = NORMALIZATION_DIR / "sources.yml"
TAGS_DB = NORMALIZATION_DIR / "tags.yml"

AUTHORS_HEADER = """# Author normalization database.
# Canonical author names should use ASCII, full first name, middle initial(s)
# when known, and full last name. Add observed variants under aliases.
# Generated by scripts/build_normalization_db.py; edit by hand as needed."""

SOURCES_HEADER = """# Source/venue normalization database.
# Canonical sources should use the preferred venue name without publication
# years. Add abbreviations or alternate spellings under aliases.
# Generated by scripts/build_normalization_db.py; edit by hand as needed."""

TAGS_HEADER = """# Tag normalization database.
# Canonical tags should use full spelling instead of acronyms. Add observed
# variants, abbreviations, plural/singular forms, and casing variants under aliases.
# Generated by scripts/build_normalization_db.py; edit by hand as needed."""


def as_list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else []


def load_metadata(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    return data if isinstance(data, dict) else {}


def collect_values(metadata_root: Path) -> tuple[Counter[str], Counter[str], Counter[str]]:
    authors: Counter[str] = Counter()
    sources: Counter[str] = Counter()
    tags: Counter[str] = Counter()
    for metadata_path in sorted(metadata_root.rglob("metadata.yml")):
        data = load_metadata(metadata_path)
        for author in as_list(data.get("authors")):
            author_text = str(author).strip()
            if author_text:
                authors[author_text] += 1

        source = str(data.get("source") or "").strip()
        if source:
            sources[source] += 1

        for tag in as_list(data.get("tags")):
            tag_text = str(tag).strip()
            if tag_text:
                tags[tag_text] += 1
    return authors, sources, tags


def existing_entries(path: Path, field: str) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    entries = load_yaml(path).get(field)
    return [entry for entry in entries if isinstance(entry, dict)] if isinstance(entries, list) else []


def author_quality(name: str, count: int) -> tuple[int, int, int, int, str]:
    parsed = parse_author(name)
    if parsed is None:
        return (0, 0, 0, count, name)
    no_edge_initials = int(not parsed.first_is_initial and not parsed.last_is_initial)
    ascii_only = int(ascii_clean(name) == name)
    middle_initials = sum(1 for part in parsed.middle if len(part.rstrip(".")) == 1)
    return (no_edge_initials, ascii_only, middle_initials, count, name)


def choose_author_canonical(names: list[str], counts: Counter[str]) -> str:
    best = max(names, key=lambda name: author_quality(name, counts[name]))
    return canonical_author_display(best)


def merge_aliases(canonical: str, values: list[str]) -> list[str]:
    aliases = {
        ascii_clean(value)
        for value in values
        if ascii_clean(value) and ascii_clean(value) != canonical
    }
    return sorted(aliases, key=str.casefold)


def build_author_entries(
    values: Counter[str],
    *,
    existing: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    canonical_to_values: dict[str, set[str]] = defaultdict(set)
    key_to_existing: dict[str, str] = {}
    for entry in existing:
        canonical = str(entry.get("canonical") or "").strip()
        if not canonical:
            continue
        canonical_to_values[canonical].add(canonical)
        for alias in entry_aliases(entry):
            canonical_to_values[canonical].add(alias)
        for value in canonical_to_values[canonical]:
            key_to_existing[author_key(value)] = canonical

    unmatched: dict[str, list[str]] = defaultdict(list)
    for value in values:
        key = author_key(value)
        canonical = key_to_existing.get(key)
        if canonical:
            canonical_to_values[canonical].add(value)
        else:
            unmatched[key].append(value)

    parsed_by_initial: dict[str, list[str]] = defaultdict(list)
    for names in unmatched.values():
        for name in names:
            key = author_initial_last_key(name)
            if key:
                parsed_by_initial[key].append(name)

    assigned: set[str] = set()
    for initial_key, names in parsed_by_initial.items():
        parsed_names = [(name, parse_author(name)) for name in names]
        full_first_names = {
            parsed.first.casefold()
            for _, parsed in parsed_names
            if parsed is not None and not parsed.first_is_initial and not parsed.last_is_initial
        }
        if len(full_first_names) != 1:
            continue
        canonical = choose_author_canonical(names, values)
        canonical_to_values[canonical].update(names)
        assigned.update(names)

    for names in unmatched.values():
        remaining = [name for name in names if name not in assigned]
        if not remaining:
            continue
        canonical = choose_author_canonical(remaining, values)
        canonical_to_values[canonical].update(remaining)

    entries = []
    for canonical in sorted(canonical_to_values, key=str.casefold):
        aliases = merge_aliases(canonical, sorted(canonical_to_values[canonical]))
        entry: dict[str, Any] = {"canonical": canonical}
        if aliases:
            entry["aliases"] = aliases
        entries.append(entry)
    return entries


def build_source_entries(
    values: Counter[str],
    *,
    existing: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    canonical_to_values: dict[str, set[str]] = defaultdict(set)
    key_to_existing: dict[str, str] = {}
    for entry in existing:
        canonical = str(entry.get("canonical") or "").strip()
        if not canonical:
            continue
        canonical_to_values[canonical].add(canonical)
        for alias in entry_aliases(entry):
            canonical_to_values[canonical].add(alias)
        for value in canonical_to_values[canonical]:
            key_to_existing[source_key(value)] = canonical

    unmatched: dict[str, list[str]] = defaultdict(list)
    for value in values:
        key = source_key(value)
        canonical = key_to_existing.get(key)
        if canonical:
            canonical_to_values[canonical].add(value)
        else:
            unmatched[key].append(value)

    for names in unmatched.values():
        best = max(names, key=lambda name: (values[name], len(name), name))
        canonical = canonical_source_display(best)
        canonical_to_values[canonical].update(names)

    entries = []
    for canonical in sorted(canonical_to_values, key=str.casefold):
        aliases = merge_aliases(canonical, sorted(canonical_to_values[canonical]))
        entry: dict[str, Any] = {"canonical": canonical}
        if aliases:
            entry["aliases"] = aliases
        entries.append(entry)
    return entries


def _is_short_acronym_tag(tag: str) -> bool:
    return bool(re.fullmatch(r"[A-Z0-9][A-Z0-9+./#*-]{1,}(?:\s+[A-Z0-9+./#*-]+)?", tag))


def _tag_canonical_score(tag: str, counts: Counter[str]) -> tuple[int, int, int, int, str]:
    expanded = expand_tag_acronyms(tag)
    uses_full_spelling = int(expanded == tag and not _is_short_acronym_tag(tag))
    capitalized = int(tag[:1].isupper() and tag[1:] != tag[1:].upper())
    return (uses_full_spelling, capitalized, counts[tag], -len(tag), tag)


def choose_tag_canonical(values: list[str], counts: Counter[str]) -> str:
    expanded_values = [expand_tag_acronyms(value) for value in values]
    candidates = sorted(set([*values, *expanded_values]))
    for value in expanded_values:
        if value not in counts:
            counts[value] += sum(counts[raw] for raw in values if expand_tag_acronyms(raw) == value)
    return max(candidates, key=lambda tag: _tag_canonical_score(tag, counts)).strip()


def build_tag_entries(
    values: Counter[str],
    *,
    existing: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    canonical_to_values: dict[str, set[str]] = defaultdict(set)
    key_to_existing: dict[str, str] = {}
    for entry in existing:
        canonical = str(entry.get("canonical") or "").strip()
        if not canonical:
            continue
        canonical_to_values[canonical].add(canonical)
        for alias in entry_aliases(entry):
            canonical_to_values[canonical].add(alias)
        for value in canonical_to_values[canonical]:
            key_to_existing[tag_key(value)] = canonical

    unmatched: dict[str, list[str]] = defaultdict(list)
    counts = Counter(values)
    for value in values:
        expanded = expand_tag_acronyms(value)
        canonical = key_to_existing.get(tag_key(value))
        if canonical is None and expanded != value:
            canonical = key_to_existing.get(tag_key(expanded))
        if canonical:
            canonical_to_values[canonical].add(value)
            if expanded != value:
                canonical_to_values[canonical].add(expanded)
            continue

        dedupe_key = tag_dedupe_key(expanded)
        unmatched[dedupe_key].append(value)
        if expanded != value:
            unmatched[dedupe_key].append(expanded)
            counts[expanded] += values[value]

    for names in unmatched.values():
        unique_names = sorted(set(names))
        canonical = choose_tag_canonical(unique_names, counts)
        canonical_to_values[canonical].update(unique_names)

    entries = []
    for canonical in sorted(canonical_to_values, key=str.casefold):
        aliases = merge_aliases(canonical, sorted(canonical_to_values[canonical]))
        entry: dict[str, Any] = {"canonical": canonical}
        if aliases:
            entry["aliases"] = aliases
        entries.append(entry)
    return entries


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build starter author/source/tag normalization databases."
    )
    parser.add_argument(
        "--update",
        action="store_true",
        help="Merge newly observed names/sources/tags into existing databases.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Rebuild databases from scratch even if they already exist.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print counts without writing database files.",
    )
    parser.add_argument(
        "--only",
        nargs="+",
        choices=("authors", "sources", "tags"),
        default=("authors", "sources", "tags"),
        help="Build only the selected normalization database(s).",
    )
    args = parser.parse_args()

    if args.update and args.force:
        parser.error("--update and --force are mutually exclusive")

    selected = set(args.only)
    selected_paths = {
        "authors": AUTHORS_DB,
        "sources": SOURCES_DB,
        "tags": TAGS_DB,
    }
    existing_selected = [
        name for name, path in selected_paths.items() if name in selected and path.exists()
    ]
    if not args.update and not args.force and existing_selected and not args.dry_run:
        print(
            "Normalization database(s) already exist for: "
            + ", ".join(existing_selected)
            + ". Use --update to merge new values or --force to rebuild.",
            file=sys.stderr,
        )
        return 2

    authors, sources, tags = collect_values(METADATA_ROOT)
    author_entries: list[dict[str, Any]] = []
    source_entries: list[dict[str, Any]] = []
    tag_entries: list[dict[str, Any]] = []
    if "authors" in selected:
        author_entries = build_author_entries(
            authors,
            existing=existing_entries(AUTHORS_DB, "authors") if args.update else [],
        )
        print(
            f"Observed {len(authors)} author spellings -> {len(author_entries)} author entries."
        )
    if "sources" in selected:
        source_entries = build_source_entries(
            sources,
            existing=existing_entries(SOURCES_DB, "sources") if args.update else [],
        )
        print(
            f"Observed {len(sources)} source spellings -> {len(source_entries)} source entries."
        )
    if "tags" in selected:
        tag_entries = build_tag_entries(
            tags,
            existing=existing_entries(TAGS_DB, "tags") if args.update else [],
        )
        print(f"Observed {len(tags)} tag spellings -> {len(tag_entries)} tag entries.")

    if args.dry_run:
        return 0

    if "authors" in selected:
        dump_yaml(AUTHORS_DB, {"version": 1, "authors": author_entries}, header=AUTHORS_HEADER)
        print(f"Wrote {AUTHORS_DB.relative_to(KB_DIR)}")
    if "sources" in selected:
        dump_yaml(SOURCES_DB, {"version": 1, "sources": source_entries}, header=SOURCES_HEADER)
        print(f"Wrote {SOURCES_DB.relative_to(KB_DIR)}")
    if "tags" in selected:
        dump_yaml(TAGS_DB, {"version": 1, "tags": tag_entries}, header=TAGS_HEADER)
        print(f"Wrote {TAGS_DB.relative_to(KB_DIR)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
