"""Generate the metadata reference and validate its example template."""

from __future__ import annotations

import argparse
import json
import textwrap
from typing import Any

import yaml

from knowledge_base.config import KB_DIR, REPO_ROOT
from knowledge_base.metadata import DEFAULT_AUDIT_STATUS, REQUIRED_FIELDS, VALID_FIELDS, MetadataRecord

TEMPLATE_PATH = KB_DIR / "docs" / "templates" / "metadata.yml"
REFERENCE_PATH = REPO_ROOT / "docs" / "METADATA.md"


def validate_template(template: str) -> None:
    data = yaml.safe_load(template)
    if not isinstance(data, dict) or tuple(data) != VALID_FIELDS:
        raise ValueError("Template must contain every metadata field in canonical order.")
    if missing := [name for name in REQUIRED_FIELDS if data[name] is None]:
        raise ValueError(f"Template has null required fields: {', '.join(missing)}")
    MetadataRecord.model_validate(data)


def schema_type(field: dict[str, Any]) -> str:
    if "anyOf" in field:
        return " or ".join(schema_type(option) for option in field["anyOf"])
    if field["type"] == "array":
        return f"list of {schema_type(field['items'])} values"
    return field["type"]


def render_reference(template: str) -> str:
    validate_template(template)
    lines = [
        "# Paper metadata",
        "",
        "<!-- Generated by knowledge_base.scripts.generate_metadata_docs; do not edit directly. -->",
        "",
        "The authoritative schema is `MetadataRecord` in",
        "[`knowledge_base/metadata.py`](../knowledge_base/metadata.py).",
        "Field descriptions, types, defaults, allowed values, and audit requirements below come from that model.",
        "Import schema constants directly from `knowledge_base.metadata`; `knowledge_base.config` only defines paths.",
        "",
        "## Updating this reference",
        "",
        "Edit the model and, when needed, the YAML template, then regenerate from the repository root:",
        "",
        "```bash",
        "./dev run --frozen python -m knowledge_base.scripts.generate_metadata_docs",
        "```",
        "",
        "Validate the template and check that this reference is current without writing files:",
        "",
        "```bash",
        "./dev run --frozen python -m knowledge_base.scripts.generate_metadata_docs --check",
        "```",
        "",
        "## Loading and auditing",
        "",
        "The loader rejects unknown fields and nested values where scalars are expected.",
        "It trims scalar text, treats null values as empty, and normalizes list fields to tuples internally.",
        "A scalar supplied for a list field becomes a one-element list; empty elements are removed.",
        "Years retain integer or string form; booleans and collections are rejected.",
        "",
        "Loader defaults allow incomplete imported records to be read.",
        "Required below means the metadata audit requires the field to be present and non-null on disk;",
        "it does not mean the loader rejects missing fields. The audit also checks content quality.",
        "Blank type and audit status values are tolerated by the loader but fail the audit's allowed-value checks.",
        f"New imports use `{DEFAULT_AUDIT_STATUS}` for audit status; a missing status loads as an empty string.",
        "Descriptions include editorial guidance that is not all enforced by Pydantic.",
        "",
        "## Fields",
    ]
    for name, field in MetadataRecord.model_json_schema()["properties"].items():
        required = "yes" if name in REQUIRED_FIELDS else "no"
        lines.extend(
            [
                "",
                f"### `{name}`",
                "",
                f"Type: {schema_type(field)}. Loader default: `{json.dumps(field['default'])}`. Required: {required}.",
                "",
                textwrap.fill(field["description"], width=110),
            ]
        )
        if "enum" in field:
            lines.extend(["", "Allowed non-empty values:", ""])
            lines.extend(f"- `{value}`" for value in field["enum"] if value)
    lines.extend(
        [
            "",
            "## Example template",
            "",
            "This illustrative example is copied from",
            "[`metadata.yml`](../knowledge_base/docs/templates/metadata.yml) and validated against the model.",
            "Replace its placeholder values with verified paper metadata.",
            "",
            "```yaml",
            template.rstrip(),
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Validate template and fail if the reference is stale.")
    args = parser.parse_args(argv)
    expected = render_reference(TEMPLATE_PATH.read_text(encoding="utf-8"))
    if args.check:
        if not REFERENCE_PATH.exists() or REFERENCE_PATH.read_text(encoding="utf-8") != expected:
            parser.exit(1, "docs/METADATA.md is stale; run this command without --check to regenerate it.\n")
        print("Metadata template and generated reference are current.")
    else:
        REFERENCE_PATH.write_text(expected, encoding="utf-8")
        print("Generated docs/METADATA.md; metadata template is valid.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
