'use strict';
(function(){
  const app=document.getElementById('an-app'); if(!app) return;
  const data=window.analyticsData;
  if(!data||!data.metrics){app.innerHTML='<p class="an-error">Analytics data is unavailable. Run <code>mkdocs build</code> to regenerate it.</p>';return;}
  const metrics=data.metrics||{};
  const barSections=[['an-authors',data.authors],['an-sources',data.sources],['an-super-categories',data.superCategories],['an-tags',data.tags],['an-types',data.types]];
  const metricRoot=document.getElementById('an-metrics'),limitSelects=Array.from(document.querySelectorAll('[data-limit-for]')),authorKicker=document.getElementById('an-author-kicker'),yearRoot=document.getElementById('an-years'),yearAxis=document.getElementById('an-year-axis'),yearTooltip=document.getElementById('an-year-tooltip');
  let yearAxisTicks=[];
  renderMetrics(); renderYears(); renderAllBars();
  limitSelects.forEach(select=>select.addEventListener('change',()=>renderBarSection(select.getAttribute('data-limit-for'))));
  app.addEventListener('click',e=>{const more=e.target.closest('.an-more');if(more)showMoreBars(more.getAttribute('data-more-for'));});
  yearRoot.addEventListener('pointerover',e=>{const bin=e.target.closest('.an-year');if(bin)showYearTooltip(bin);});
  yearRoot.addEventListener('pointermove',e=>{const bin=e.target.closest('.an-year');if(bin)positionYearTooltipForBar(bin);});
  yearRoot.addEventListener('pointerout',e=>{const bin=e.target.closest('.an-year');if(bin&&!bin.contains(e.relatedTarget))hideYearTooltip();});
  yearRoot.addEventListener('focusin',e=>{const bin=e.target.closest('.an-year');if(bin)showYearTooltip(bin);});
  yearRoot.addEventListener('focusout',e=>{if(e.target.closest('.an-year'))hideYearTooltip();});
  yearRoot.addEventListener('touchstart',handleYearTouch,{passive:true});
  yearRoot.addEventListener('touchmove',handleYearTouch,{passive:true});
  yearRoot.addEventListener('touchend',hideYearTooltip,{passive:true});
  yearRoot.addEventListener('touchcancel',hideYearTooltip,{passive:true});
  if(window.ResizeObserver&&yearAxis){new ResizeObserver(renderYearAxis).observe(yearAxis);}else{window.addEventListener('resize',renderYearAxis);}
  function renderMetrics(){const yearRange=metrics.minYear&&metrics.maxYear?metrics.minYear+' - '+metrics.maxYear:'Unknown';metricRoot.innerHTML=[card('Papers',metrics.totalPapers),card('Authors',metrics.uniqueAuthors),card('Sources',metrics.uniqueSources),card('Tags',metrics.uniqueTags),card('Year Range',yearRange),card('arXiv IDs',metrics.arxivPapers),card('DOIs',metrics.doiPapers)].join('');}
  function renderYears(){const rows=Array.isArray(data.years)?data.years:[],root=yearRoot,max=Math.max(1,...rows.map(r=>r.count||0));if(!rows.length){root.innerHTML='<p class="an-empty">No dated papers.</p>';if(yearAxis)yearAxis.innerHTML='';yearAxisTicks=[];return;}const bars=rows.slice().reverse().map(r=>{const label=r.label||r.year||'',count=r.count||0,tip=label+': '+count,pct=Math.max(2,Math.round(count/max*100));return '<span class="an-year" data-range="'+escAttr(label)+'" data-count="'+escAttr(count)+'" tabindex="0" aria-describedby="an-year-tooltip" aria-label="'+escAttr(tip)+'"><span class="an-year-label" title="'+escAttr(label)+'">'+esc(label)+'</span><span class="an-year-count">'+esc(count)+'</span><span class="an-year-track"><i style="--an-w:'+pct+'%"></i></span></span>';}).join('');root.innerHTML=bars;if(yearAxis)yearAxis.innerHTML='';yearAxisTicks=[];}
  function renderAllBars(){authorKicker.textContent=plural(metrics.uniqueAuthors||0,'unique author')+' counted across author lists';barSections.forEach(([id,rows])=>renderBars(id,rows,selectedLimit(id)));}
  function renderBarSection(id){const section=barSections.find(([sectionId])=>sectionId===id);if(section)renderBars(section[0],section[1],selectedLimit(id));}
  function selectedLimit(id){const select=limitSelects.find(el=>el.getAttribute('data-limit-for')===id);if(!select)return Infinity;const value=select.value;return value==='all'?Infinity:(parseInt(value,10)||5);}
  function renderBars(id,rows,limit){const root=document.getElementById(id),allItems=(Array.isArray(rows)?rows:[]).filter(r=>r&&r.count>0),visibleItems=allItems.slice(0,limit),max=Math.max(1,...visibleItems.map(r=>r.count));if(!allItems.length){root.innerHTML='<p class="an-empty">No data.</p>';return;}const bars=visibleItems.map(r=>'<div class="an-bar"><span class="an-bar-label" title="'+escAttr(r.label)+'">'+esc(r.label)+'</span><span class="an-bar-track"><span class="an-bar-fill" style="--an-w:'+Math.round(r.count/max*100)+'%"></span></span><span class="an-bar-count">'+esc(r.count)+'</span></div>').join('');const hidden=allItems.length-visibleItems.length;root.innerHTML=bars+(hidden>0?'<button class="an-more" type="button" data-more-for="'+escAttr(id)+'" aria-label="Show more '+escAttr(id.replace(/^an-/,'').replace(/-/g,' '))+'">'+esc(plural(hidden,'more item'))+' not displayed</button>':'');}
  function showMoreBars(id){const select=limitSelects.find(el=>el.getAttribute('data-limit-for')===id);if(!select)return;const current=selectedLimit(id),options=Array.from(select.options),next=options.find(option=>option.value==='all'||(parseInt(option.value,10)||0)>current);if(!next)return;select.value=next.value;renderBarSection(id);select.focus({preventScroll:true});}
  function showYearTooltip(bin){if(!yearTooltip)return;const range=bin.getAttribute('data-range')||'',count=bin.getAttribute('data-count')||'0';yearTooltip.innerHTML=esc(range)+'<span>'+esc(plural(parseInt(count,10)||0,'paper'))+'</span>';yearTooltip.hidden=false;yearTooltip.classList.add('is-visible');positionYearTooltipForBar(bin);}
  function showYearTouchTooltip(bin,touch){if(!yearTooltip||!bin||!touch)return;const range=bin.getAttribute('data-range')||'',count=bin.getAttribute('data-count')||'0';yearTooltip.innerHTML=esc(range)+'<span>'+esc(plural(parseInt(count,10)||0,'paper'))+'</span>';yearTooltip.hidden=false;yearTooltip.classList.add('is-visible');positionYearTooltip(touch.clientX,touch.clientY);}
  function hideYearTooltip(){if(!yearTooltip)return;yearTooltip.classList.remove('is-visible');yearTooltip.hidden=true;}
  function positionYearTooltip(x,y){if(!yearTooltip||yearTooltip.hidden)return;const pad=8;yearTooltip.style.left=Math.min(Math.max(x,pad),window.innerWidth-pad)+'px';yearTooltip.style.top=Math.min(Math.max(y,pad),window.innerHeight-pad)+'px';}
  function positionYearTooltipForBar(bin){const anchor=bin.querySelector('.an-year-track')||bin,rect=anchor.getBoundingClientRect();positionYearTooltip(rect.left+rect.width/2,rect.top);}
  function handleYearTouch(e){const touch=e.touches&&e.touches[0];if(!touch)return;const target=document.elementFromPoint(touch.clientX,touch.clientY),bin=target&&target.closest?target.closest('.an-year'):null;if(bin&&yearRoot.contains(bin)){showYearTouchTooltip(bin,touch);}}
  function renderYearAxis(){if(!yearAxis)return;const ticks=sampleAxisTicks(yearAxisTicks,yearAxis);yearAxis.innerHTML=ticks.map(t=>'<span class="an-year-axis-tick"'+tickEdgeAttr(t)+' style="--an-x:'+escAttr(t.x)+'%">'+esc(t.label)+'</span>').join('');}
  function binWidth(row){const width=parseFloat(row&&row.width);if(Number.isFinite(width)&&width>0)return width;const start=parseInt(row&&row.start,10);return Number.isFinite(start)&&start<1941?10:5;}
  function axisTickCandidates(rows,total){const ticks=[];let offset=0;rows.forEach(row=>{const width=binWidth(row),start=parseInt(row.start,10),end=parseInt(row.end,10),left=offset/total*100,right=(offset+width)/total*100;if(Number.isFinite(end)&&end<1940){ticks.push({label:'Pre-1940',x:((left+right)/2).toFixed(4),kind:'pre'});}else{if(Number.isFinite(start)&&start<=1941){ticks.push({label:'1940',x:left.toFixed(4),kind:'year'});}if(Number.isFinite(end)){ticks.push({label:String(end),x:right.toFixed(4),kind:'year'});}}offset+=width;});if(ticks.length)ticks[ticks.length-1].required=true;return ticks;}
  function sampleAxisTicks(ticks,axis){const all=Array.isArray(ticks)?ticks.filter(Boolean):[];if(all.length<=1)return all;const width=axis.clientWidth||axis.getBoundingClientRect().width||0;if(width<=0)return all.filter(t=>t.required||t.kind!=='year');const yearTicks=all.filter(t=>t.kind==='year'),preTicks=all.filter(t=>t.kind!=='year');for(const includePre of [true,false]){for(let step=1;step<=Math.max(1,yearTicks.length);step++){const chosen=yearTicks.filter((t,i)=>t.required||i%step===0);if(includePre)chosen.unshift(...preTicks);const ordered=dedupeTicks(chosen).sort((a,b)=>parseFloat(a.x)-parseFloat(b.x));if(!hasTickCollisions(ordered,axis,width))return ordered;}}return all.filter(t=>t.required);}
  function dedupeTicks(ticks){const seen=new Set();return ticks.filter(t=>{const key=t.label+'@'+t.x;if(seen.has(key))return false;seen.add(key);return true;});}
  function hasTickCollisions(ticks,axis,width){let lastRight=-Infinity;const gap=6;for(const tick of ticks){const box=tickBox(tick,axis,width);if(box.left<0||box.right>width||box.left<lastRight+gap)return true;lastRight=box.right;}return false;}
  function tickBox(tick,axis,width){const labelWidth=measureTickLabel(tick.label,axis)+8,x=parseFloat(tick.x)/100*width,edge=tickEdge(tick);let left=x-labelWidth/2;if(edge==='start')left=x;if(edge==='end')left=x-labelWidth;return{left,right:left+labelWidth};}
  function measureTickLabel(label,axis){const style=getComputedStyle(axis),canvas=measureTickLabel.canvas||(measureTickLabel.canvas=document.createElement('canvas')),ctx=canvas.getContext('2d');ctx.font=[style.fontStyle,style.fontVariant,style.fontWeight,style.fontSize,style.fontFamily].filter(Boolean).join(' ');return ctx.measureText(String(label||'')).width;}
  function tickEdge(tick){const x=parseFloat(tick&&tick.x);if(x<=0.001)return'start';if(x>=99.999)return'end';return'';}
  function tickEdgeAttr(tick){const edge=tickEdge(tick);return edge?' data-edge="'+edge+'"':'';}
  function card(label,value){return '<div class="an-metric"><strong>'+esc(value==null?'':value)+'</strong><span>'+esc(label)+'</span></div>';}
  function plural(n,s,p){return n+' '+(n===1?s:(p||s+'s'));}
  function norm(v){return String(v||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'');}
  function esc(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
  function escAttr(v){return esc(v).replace(/`/g,'&#96;');}
})();
