'use strict';
(function(){
  const app=document.getElementById('tl-app'); if(!app) return;
  const data=window.timelineData;
  if(!data||!Array.isArray(data.papers)||!data.meta){app.innerHTML='<p class="tl-error">Timeline data is unavailable. Run <code>mkdocs build</code> to regenerate it.</p>';return;}
  const UNCATEGORIZED=(data.meta&&data.meta.uncategorizedCategory)||'Uncategorized';
  const UNCATEGORIZED_SET=new Set([UNCATEGORIZED,'Other']);
  const PALETTE=[{h:213,s:76,l:42},{h:152,s:70,l:35},{h:31,s:82,l:43},{h:271,s:62,l:44},{h:334,s:58,l:44},{h:12,s:72,l:42},{h:188,s:72,l:36}];
  const svg=document.getElementById('tl-svg'),svgWrap=document.getElementById('tl-svg-wrap'),stage=document.querySelector('.tl-stage'),toolbar=document.querySelector('.tl-stage-toolbar'),axisTop=document.getElementById('tl-axis-top'),status=document.getElementById('tl-status'),legend=document.getElementById('tl-legend'),modal=document.getElementById('tl-modal'),modalTitle=document.getElementById('tl-modal-title'),modalBody=document.getElementById('tl-modal-body'),modalClose=document.getElementById('tl-modal-close'),settings=document.getElementById('tl-settings'),settingsToggle=document.getElementById('tl-settings-toggle'),settingsToggleLabel=document.getElementById('tl-settings-toggle-label'),chip=document.getElementById('tl-selection-chip'),form=document.getElementById('tl-search-form'),search=document.getElementById('tl-search'),yearStart=document.getElementById('tl-year-start'),yearEnd=document.getElementById('tl-year-end'),reset=document.getElementById('tl-reset'),zoomIn=document.getElementById('tl-zoom-in'),zoomOut=document.getElementById('tl-zoom-out'),zoomReset=document.getElementById('tl-zoom-reset'),dotsToggle=document.getElementById('tl-show-dots'),modeButtons=Array.from(app.querySelectorAll('[data-tl-mode]'));
  syncTimelineHeaderHeight(); window.addEventListener('resize',syncTimelineHeaderHeight); if(window.visualViewport)window.visualViewport.addEventListener('resize',syncTimelineHeaderHeight);
  const hslCache=new Map(),colorCache=new Map(),subColorCache=new Map(),jitterCache=new Map();
  const papers=data.papers.map(p=>{const y=Number.isInteger(p.year)?p.year:null;const sup=p.superCategory||UNCATEGORIZED;const cat=p.category||UNCATEGORIZED;const sub=p.subCategory||'';return Object.assign({},p,{year:y,superCategory:sup,category:cat,subCategory:sub,searchText:norm([p.label,p.title,p.authorShort,Array.isArray(p.authors)?p.authors.join(' '):'',y||'',sup,cat,sub,Array.isArray(p.tags)?p.tags.join(' '):'',p.summary||'',p.abstract||''].join(' '))});});
  const paperById=new Map(papers.map(p=>[p.id,p]));
  const plotted=papers.filter(p=>Number.isInteger(p.year));
  const minYear=data.meta.minYear||Math.min(...plotted.map(p=>p.year)),maxYear=data.meta.maxYear||Math.max(...plotted.map(p=>p.year)),yearBins=normalizeYearBins((data.meta||{}).yearBins,minYear,maxYear),defaultStartYear=minYear;
  const state={mode:'super',activeSupers:new Set(superOrder()),query:'',selectedId:null,yearStart:defaultStartYear,yearEnd:maxYear,showDots:true,layout:null,dragZoom:null,renderPending:false,suppressCanvasClick:false,clearSelectionTimer:null};
  const hashId=readPaperHash(); if(hashId&&paperById.has(hashId)) state.selectedId=hashId;
  yearStart.value=state.yearStart; yearEnd.value=state.yearEnd; dotsToggle.checked=state.showDots;
  if(settings&&settingsToggle&&window.matchMedia&&window.matchMedia('(max-width: 680px)').matches){settings.classList.add('is-collapsed');settingsToggle.setAttribute('aria-expanded','false');if(settingsToggleLabel)settingsToggleLabel.textContent='Show Settings';}
  form.addEventListener('submit',e=>{e.preventDefault();const first=filtered()[0];if(first) selectPaper(first.id,true);});
  search.addEventListener('input',()=>{state.query=search.value.trim();render();});
  yearStart.addEventListener('change',syncYears); yearEnd.addEventListener('change',syncYears);
  dotsToggle.addEventListener('change',()=>{state.showDots=dotsToggle.checked;render();});
  zoomIn.addEventListener('click',()=>zoomBy(.5));
  zoomOut.addEventListener('click',()=>zoomBy(2));
  zoomReset.addEventListener('click',resetZoom);
  reset.addEventListener('click',()=>{state.mode='super';state.activeSupers=new Set(superOrder());state.query='';state.selectedId=null;state.showDots=true;state.dragZoom=null;search.value='';dotsToggle.checked=true;resetZoom(false);setHash(null);render();});
  if(settingsToggle)settingsToggle.addEventListener('click',()=>{const collapsed=!settings.classList.contains('is-collapsed');settings.classList.toggle('is-collapsed',collapsed);settingsToggle.setAttribute('aria-expanded',String(!collapsed));if(settingsToggleLabel)settingsToggleLabel.textContent=collapsed?'Show Settings':'Hide Settings';scheduleRender();});
  if(modalClose)modalClose.addEventListener('click',closeModalSelection);
  if(modal)modal.addEventListener('click',e=>{if(e.target===modal)closeModalSelection();});
  window.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal&&!modal.hidden)closeModalSelection();});
  modeButtons.forEach(button=>button.addEventListener('click',()=>{state.mode=button.getAttribute('data-tl-mode')||'category';render();}));
  legend.addEventListener('click',e=>{const button=e.target.closest('[data-tl-super]');if(!button)return;const next=button.getAttribute('data-tl-super');if(state.activeSupers.has(next)){state.activeSupers.delete(next);}else{state.activeSupers.add(next);}render();});
  svg.addEventListener('pointerdown',startZoomDrag);
  svg.addEventListener('pointermove',updateZoomDrag);
  svg.addEventListener('pointerup',finishZoomDrag);
  svg.addEventListener('pointercancel',cancelZoomDrag);
  svg.addEventListener('lostpointercapture',cancelZoomDrag);
  svg.addEventListener('dblclick',resetZoomFromBlank);
  svg.addEventListener('click',e=>{const target=e.target.closest('[data-paper-id]');if(target){selectPaper(target.getAttribute('data-paper-id'),true);return;}clearSelectionFromCanvas(e);});
  svg.addEventListener('keydown',e=>{if(e.key!=='Enter'&&e.key!==' ')return;const target=e.target.closest('[data-paper-id]');if(!target)return;e.preventDefault();selectPaper(target.getAttribute('data-paper-id'),true);});
  if(svgWrap)svgWrap.addEventListener('scroll',positionStickyAxes,{passive:true});
  window.addEventListener('resize',scheduleRender);
  window.addEventListener('scroll',()=>{updateStageHeight();positionStickyAxes();},{passive:true});
  window.addEventListener('popstate',()=>{const next=readPaperHash();state.selectedId=next&&paperById.has(next)?next:null;render();});
  if(window.ResizeObserver){new ResizeObserver(scheduleRender).observe(svgWrap);}
  render();
  function syncYears(){const a=clampYear(parseInt(yearStart.value,10)),b=clampYear(parseInt(yearEnd.value,10));setYearRange(a,b,true);}
  function updateYearInputs(){yearStart.value=state.yearStart;yearEnd.value=state.yearEnd;}
  function setYearRange(a,b,doRender){const start=clampYear(a),end=clampYear(b);state.yearStart=Math.min(start,end);state.yearEnd=Math.max(start,end);updateYearInputs();if(doRender!==false)render();}
  function resetZoom(doRender){setYearRange(defaultStartYear,maxYear,doRender);}
  function zoomBy(factor){const fullSpan=maxYear-minYear+1,currentSpan=state.yearEnd-state.yearStart+1,nextSpan=clamp(Math.round(currentSpan*factor),1,fullSpan),center=(state.yearStart+state.yearEnd)/2;let start=Math.round(center-(nextSpan-1)/2),end=start+nextSpan-1;if(start<minYear){end+=minYear-start;start=minYear;}if(end>maxYear){start-=end-maxYear;end=maxYear;}setYearRange(start,end,true);}
  function clampYear(v){return Number.isFinite(v)?Math.min(Math.max(v,minYear),maxYear):minYear;}
  function selectPaper(id,push){if(!paperById.has(id))return;state.selectedId=id;if(push)setHash(id);render();const node=svg.querySelector('[data-paper-id="'+cssEscape(id)+'"]');if(node&&node.focus)node.focus({preventScroll:true});}
  function clearSelectionFromCanvas(e){if(state.suppressCanvasClick){state.suppressCanvasClick=false;return;}if(!state.selectedId||!state.layout)return;const p=svgPoint(e);if(!pointInsidePlot(p.x,p.y))return;cancelClearSelection();state.clearSelectionTimer=window.setTimeout(()=>{state.clearSelectionTimer=null;if(!state.selectedId)return;state.selectedId=null;setHash(null);render();},230);}
  function closeModalSelection(){if(!state.selectedId)return;state.selectedId=null;setHash(null);render();}
  function cancelClearSelection(){if(!state.clearSelectionTimer)return;window.clearTimeout(state.clearSelectionTimer);state.clearSelectionTimer=null;}
  function startZoomDrag(e){if(e.button!==0||!state.layout||e.target.closest('[data-paper-id]'))return;if(e.detail>=2){cancelClearSelection();return;}const p=svgPoint(e);if(!pointInsidePlot(p.x,p.y))return;state.dragZoom={pointerId:e.pointerId,startX:clamp(p.x,state.layout.margin.left,state.layout.margin.left+state.layout.innerW),endX:clamp(p.x,state.layout.margin.left,state.layout.margin.left+state.layout.innerW),moved:false};if(svg.setPointerCapture)svg.setPointerCapture(e.pointerId);}
  function updateZoomDrag(e){if(!state.dragZoom||state.dragZoom.pointerId!==e.pointerId)return;const p=svgPoint(e),left=state.layout.margin.left,right=left+state.layout.innerW,threshold=9;state.dragZoom.endX=clamp(p.x,left,right);state.dragZoom.moved=state.dragZoom.moved||Math.abs(state.dragZoom.endX-state.dragZoom.startX)>=threshold;if(!state.dragZoom.moved){clearDragZoom();return;}drawDragZoom();e.preventDefault();}
  function finishZoomDrag(e){if(!state.dragZoom||state.dragZoom.pointerId!==e.pointerId)return;updateZoomDrag(e);const drag=state.dragZoom,apply=drag.moved&&Math.abs(drag.endX-drag.startX)>=18;if(svg.releasePointerCapture)try{svg.releasePointerCapture(e.pointerId);}catch(err){}state.dragZoom=null;clearDragZoom();if(drag.moved){state.suppressCanvasClick=true;window.setTimeout(()=>{state.suppressCanvasClick=false;},0);}if(!apply)return;const a=yearForSvgX(Math.min(drag.startX,drag.endX)),b=yearForSvgX(Math.max(drag.startX,drag.endX));if(a===b)return;setYearRange(a,b,true);e.preventDefault();}
  function cancelZoomDrag(e){if(!state.dragZoom||e.pointerId!==undefined&&state.dragZoom.pointerId!==e.pointerId)return;state.dragZoom=null;clearDragZoom();}
  function resetZoomFromBlank(e){if(!state.layout||e.target.closest('[data-paper-id]'))return;const p=svgPoint(e);if(!pointInsidePlot(p.x,p.y))return;cancelClearSelection();state.dragZoom=null;clearDragZoom();resetZoom(true);e.preventDefault();}
  function pointInsidePlot(x,y){const l=state.layout;if(!l)return false;return x>=l.margin.left&&x<=l.margin.left+l.innerW&&y>=l.margin.top-22&&y<=l.bottom+12;}
  function svgPoint(e){if(svg.createSVGPoint&&svg.getScreenCTM){const pt=svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const ctm=svg.getScreenCTM();if(ctm)return pt.matrixTransform(ctm.inverse());}const rect=svg.getBoundingClientRect(),viewBox=svg.viewBox.baseVal;return{x:(e.clientX-rect.left)/Math.max(1,rect.width)*viewBox.width,y:(e.clientY-rect.top)/Math.max(1,rect.height)*viewBox.height};}
  function yearForSvgX(x){const l=state.layout,start=scaleForYear(state.yearStart),end=scaleForYear(state.yearEnd,true),v=start+clamp((x-l.margin.left)/Math.max(1,l.innerW),0,1)*(end-start);return yearForScaleValue(v);}
  function yearForScaleValue(v){let nearest=minYear,nearestDist=Infinity;for(let y=minYear;y<=maxYear;y++){const left=scaleForYear(y),right=scaleForYear(y,true);if(v>=left&&v<=right)return y;const mid=(left+right)/2,dist=Math.abs(v-mid);if(dist<nearestDist){nearest=y;nearestDist=dist;}}return nearest;}
  function clearDragZoom(){svg.querySelectorAll('.tl-drag-zoom').forEach(node=>node.remove());}
  function drawDragZoom(){clearDragZoom();const drag=state.dragZoom,l=state.layout;if(!drag||!l)return;const x1=Math.min(drag.startX,drag.endX),x2=Math.max(drag.startX,drag.endX),top=l.margin.top-6,bottom=l.bottom+8,g=append(svg,'g',{class:'tl-drag-zoom'});append(g,'rect',{x:x1,y:top,width:Math.max(1,x2-x1),height:bottom-top,rx:4,class:'tl-drag-band'});append(g,'line',{x1:x1,x2:x1,y1:top,y2:bottom,class:'tl-drag-edge'});append(g,'line',{x1:x2,x2:x2,y1:top,y2:bottom,class:'tl-drag-edge'});}
  function scheduleRender(){if(state.renderPending)return;state.renderPending=true;requestAnimationFrame(()=>{state.renderPending=false;render();});}
  function updateStageHeight(){if(!stage)return;if(window.matchMedia&&window.matchMedia('(max-width: 680px)').matches){stage.style.setProperty('--tl-stage-height','30rem');return;}const rect=stage.getBoundingClientRect(),gap=12,min=Math.min(220,Math.max(140,Math.round(window.innerHeight*.22))),available=Math.floor(window.innerHeight-rect.top-gap),height=Math.max(min,available);stage.style.setProperty('--tl-stage-height',height+'px');}
  function render(){const visible=filtered(),groups=buildGroups(visible);renderLegend();renderStatus(visible,groups);renderDetail();updateStageHeight();renderSvg(groups);modeButtons.forEach(b=>b.setAttribute('aria-pressed',String(b.getAttribute('data-tl-mode')===state.mode)));}
  function filtered(){const terms=norm(state.query).split(/\s+/).filter(Boolean);return plotted.filter(p=>p.year>=state.yearStart&&p.year<=state.yearEnd&&state.activeSupers.has(p.superCategory)&&(!terms.length||terms.every(t=>p.searchText.includes(t))));}
  function buildGroups(visible){const map=new Map();visible.forEach(p=>{const d=groupDescriptor(p);if(!map.has(d.key))map.set(d.key,Object.assign({},d,{superCategory:p.superCategory,category:p.category,subCategory:p.subCategory,papers:[]}));map.get(d.key).papers.push(p);});return Array.from(map.values()).sort((a,b)=>compare(a.sort,b.sort)||a.label.localeCompare(b.label));}
  function groupDescriptor(p){const si=positive(superOrder().indexOf(p.superCategory)),ci=positive(categoryOrder().indexOf(p.category)),subs=((data.meta||{}).subCategoryOrder||{})[p.category]||[],subi=positive(p.subCategory?subs.indexOf(p.subCategory):-1);if(state.mode==='super')return{key:'super:'+p.superCategory,label:p.superCategory,pathLabel:p.superCategory,color:isUncat(p.category)?'#000000':superColor(p.superCategory),sort:[si,0,0]};if(state.mode==='sub'){const label=p.subCategory||p.category;return{key:'sub:'+p.category+'::'+(p.subCategory||'(direct)'),label:label,pathLabel:p.subCategory?p.category+' / '+p.subCategory:p.category,color:nodeColor(p.category,p.subCategory),sort:[si,ci,subi]};}return{key:'category:'+p.category,label:p.category,pathLabel:p.superCategory+' / '+p.category,color:nodeColor(p.category,''),sort:[si,ci,0]};}
  function renderSvg(groups){clear(svg);const wrapWidth=svgWrap?svgWrap.clientWidth:0,parentWidth=svg.parentElement?svg.parentElement.clientWidth:0,available=Math.max(320,Math.floor(wrapWidth||parentWidth||960)),compact=available<760,topLabels=available<680,margin={top:topLabels?54:44,right:compact?24:48,bottom:52,left:topLabels?24:(compact?204:282)},baseRowH=state.mode==='sub'?(compact?62:68):state.mode==='super'?(compact?84:92):(compact?70:78),density=densityStats(groups),rows=groups.map(g=>({group:g,rowH:rowHeightForGroup(g,baseRowH,density)})),innerW=Math.max(180,available-margin.left-margin.right),width=margin.left+innerW+margin.right,height=Math.max(420,margin.top+rows.reduce((sum,r)=>sum+r.rowH,0)+margin.bottom),bottom=height-margin.bottom;state.layout={margin:margin,innerW:innerW,width:width,height:height,bottom:bottom};svg.setAttribute('viewBox','0 0 '+width+' '+height);svg.setAttribute('width','100%');svg.setAttribute('height',height);append(svg,'rect',{x:0,y:0,width:width,height:height,class:'tl-svg-bg'});renderStickyAxes(drawGrid(svg,margin,width,bottom),margin,innerW);if(!groups.length){append(svg,'text',{x:margin.left,y:margin.top+70,class:'tl-empty-svg'},'No dated papers match the current filters.');drawDragZoom();return;}let top=margin.top;rows.forEach(row=>{const center=topLabels?top+Math.max(56,row.rowH*.64):top+row.rowH/2;drawGroup(svg,row.group,top,center,row.rowH,margin,innerW,topLabels,density,bottom);top+=row.rowH;});drawDragZoom();}
  function drawGrid(root,margin,width,bottom){const innerW=width-margin.left-margin.right,g=append(root,'g',{class:'tl-grid'}),bins=visibleYearBins(),ticks=responsiveYearTicks(yearBoundaryTicks(bins),margin,innerW);ticks.forEach(tick=>{const x=xForScaleValue(tick.value,margin,innerW),major=tick.kind!=='one'||tick.year%5===0,label=String(tick.year);append(g,'line',{x1:x,x2:x,y1:margin.top-18,y2:bottom,class:major?'tl-grid-major':'tl-grid-minor'});append(g,'text',{x:x,y:margin.top-24,class:'tl-year-label'},label);append(g,'text',{x:x,y:bottom+30,class:'tl-year-label'},label);});append(g,'line',{x1:margin.left,x2:width-margin.right,y1:margin.top-6,y2:margin.top-6,class:'tl-axis-line'});append(g,'line',{x1:margin.left,x2:width-margin.right,y1:bottom+8,y2:bottom+8,class:'tl-axis-line'});return ticks;}
  function renderStickyAxes(ticks,margin,innerW){if(!axisTop)return;const startX=axisXForSvgX(margin.left),endX=axisXForSvgX(margin.left+innerW),html=(ticks||[]).map(tick=>{const svgX=xForScaleValue(tick.value,margin,innerW),x=axisXForSvgX(svgX),edge=x<=startX+.5?'start':x>=endX-.5?'end':'';return '<span class="tl-sticky-axis-tick"'+(edge?' data-edge="'+edge+'"':'')+' style="left:'+x.toFixed(1)+'px">'+esc(tick.year)+'</span>';}).join('');axisTop.innerHTML=html;positionStickyAxes();}
  function axisXForSvgX(x){const vb=svg.viewBox&&svg.viewBox.baseVal,svgRect=svg.getBoundingClientRect(),wrapRect=svgWrap?svgWrap.getBoundingClientRect():svgRect,viewX=vb&&Number.isFinite(vb.x)?vb.x:0,viewW=vb&&vb.width?vb.width:(state.layout&&state.layout.width)||svgRect.width||1,scale=svgRect.width/Math.max(1e-6,viewW);return svgRect.left-wrapRect.left+(x-viewX)*scale+(svgWrap?svgWrap.scrollLeft||0:0);}
  function positionStickyAxes(){if(!svgWrap||!axisTop)return;const top=svgWrap.scrollTop;axisTop.style.transform='translateY('+top+'px)';}
  function yearBoundaryTicks(bins){if(!bins.length)return[];const ticks=[];bins.forEach((bin,i)=>{const leftYear=Math.max(bin.start,state.yearStart),next=bins[i+1];if(i===0||leftYear>ticks[ticks.length-1].year)ticks.push({year:leftYear,value:scaleForYear(leftYear),kind:bin.kind});if(next){const rightYear=Math.max(next.start,state.yearStart);ticks.push({year:rightYear,value:next.offset,kind:next.kind});}else{const rightYear=Math.min(bin.end,state.yearEnd);if(rightYear>ticks[ticks.length-1].year)ticks.push({year:rightYear,value:scaleForYear(rightYear,true),kind:bin.kind});}});return ticks.filter((tick,i,rows)=>i===0||tick.year!==rows[i-1].year||Math.abs(tick.value-rows[i-1].value)>1e-6);}
  function responsiveYearTicks(ticks,margin,innerW){if(ticks.length<2)return ticks;const minGap=42,withX=ticks.map(t=>Object.assign({x:xForScaleValue(t.value,margin,innerW),region:tickRegion(t.year)},t)),selected=[];['coarse','five','one'].forEach(region=>{const rows=withX.filter(t=>t.region===region);if(!rows.length)return;const gaps=rows.slice(1).map((t,i)=>t.x-rows[i].x).filter(g=>g>0),baseGap=gaps.length?Math.min(...gaps):innerW,step=Math.max(1,Math.ceil(minGap/baseGap));rows.forEach((tick,i)=>{if(i%step===0||i===rows.length-1)selected.push(tick);});});return withoutTickCollisions(selected.sort((a,b)=>a.x-b.x),minGap);}
  function withoutTickCollisions(ticks,minGap){let lastX=-Infinity;return ticks.filter(tick=>{if(tick.x-lastX<minGap)return false;lastX=tick.x;return true;});}
  function tickRegion(year){return year<1950?'coarse':year<2000?'five':'one';}
  function drawGroup(root,group,top,center,rowH,margin,innerW,topLabels,density,bottom){const lane=append(root,'g',{class:'tl-group','data-group-key':group.key}),labelMax=topLabels?Math.max(72,innerW-90):Math.max(44,margin.left-60);append(lane,'line',{x1:margin.left,x2:margin.left+innerW,y1:center,y2:center,class:'tl-lane-line'});if(topLabels){append(lane,'rect',{x:margin.left,y:top+6,width:innerW,height:34,rx:8,class:'tl-group-label-bg'});append(lane,'circle',{cx:margin.left+12,cy:top+23,r:5,fill:group.color,class:'tl-group-swatch'});fitSvgText(append(lane,'text',{x:margin.left+26,y:top+20,class:'tl-group-label'},group.label),group.label,labelMax);append(lane,'text',{x:margin.left+26,y:top+34,class:'tl-group-meta'},plural(group.papers.length,'paper'));}else{append(lane,'rect',{x:0,y:top+4,width:margin.left-18,height:rowH-8,rx:8,class:'tl-group-label-bg'});append(lane,'circle',{cx:18,cy:center,r:5,fill:group.color,class:'tl-group-swatch'});fitSvgText(append(lane,'text',{x:32,y:center-3,class:'tl-group-label'},group.label),group.label,labelMax);append(lane,'text',{x:32,y:center+14,class:'tl-group-meta'},plural(group.papers.length,'paper'));}append(lane,'path',{d:streamPath(group,center,rowH,margin,innerW,density),fill:group.color,stroke:group.color,class:'tl-stream'});if(!state.showDots)return;const byYear=groupYearCounts(group.papers),plotLeft=margin.left,plotRight=margin.left+innerW;Array.from(byYear.keys()).sort((a,b)=>a-b).forEach(year=>{const items=byYear.get(year).items.sort((a,b)=>a.label.localeCompare(b.label)),count=items.length,range=jitterRangeForYear(year,count,innerW,density),topLimit=top+(topLabels?44:14),bottomLimit=top+rowH-14,yRadius=densityRadius(count,rowH,topLimit,bottomLimit,density),dotRadius=dotRadiusForCount(count);items.forEach(p=>{const jitter=timelineJitter(group.key,year,p.id),x=xForYear(year,margin,innerW,jitter.x*range),y=clamp(center+jitter.y*yRadius,topLimit,bottomLimit),r=dotRadius||4.4;if(x-r<plotLeft||x+r>plotRight)return;drawPaper(lane,p,x,y,group.color,dotRadius,margin.top-14,bottom);});});}
  function fitSvgText(el,text,maxWidth){const value=String(text||'');el.textContent=value;if(!value||safeTextLength(el)<=maxWidth)return;const suffix='...';let lo=0,hi=value.length,best=suffix;while(lo<=hi){const mid=Math.floor((lo+hi)/2),next=value.slice(0,mid).trimEnd()+suffix;el.textContent=next;if(safeTextLength(el)<=maxWidth){best=next;lo=mid+1;}else{hi=mid-1;}}el.textContent=best;}
  function safeTextLength(el){return typeof el.getComputedTextLength==='function'?el.getComputedTextLength():el.textContent.length*7;}
  function streamPath(group,center,rowH,margin,innerW,density){const counts=groupYearCounts(group.papers),samples=[],minH=3.2,maxH=Math.max(minH,Math.min(rowH*.32,rowH/2-18)),pushSample=(year,h,endEdge)=>{const x=xForScaleValue(scaleForYear(year,endEdge),margin,innerW),last=samples[samples.length-1];if(last&&Math.abs(last.x-x)<.35){last.top=Math.min(last.top,center-h);last.bottom=Math.max(last.bottom,center+h);return;}samples.push({x:x,top:center-h,bottom:center+h});};streamSampleYears().forEach(year=>{const v=streamDensityAtYear(counts,year),h=minH+Math.pow(scaledStreamDensity(v,density),.86)*(maxH-minH);pushSample(year,h,false);});if(state.yearEnd>=state.yearStart){const endV=streamDensityAtYear(counts,state.yearEnd),endH=minH+Math.pow(scaledStreamDensity(endV,density),.86)*(maxH-minH);pushSample(state.yearEnd,endH,true);}if(!samples.length)samples.push({x:margin.left,top:center-3,bottom:center+3},{x:margin.left+innerW,top:center-3,bottom:center+3});return 'M '+samples.map(p=>p.x.toFixed(1)+' '+p.top.toFixed(1)).join(' L ')+' L '+samples.slice().reverse().map(p=>p.x.toFixed(1)+' '+p.bottom.toFixed(1)).join(' L ')+' Z';}
  function drawPaper(root,p,x,y,color,radius,guideTop,guideBottom){const g=append(root,'g',{class:'tl-paper-node','data-paper-id':p.id,tabindex:0,role:'button','aria-label':p.label+', '+p.year});append(g,'line',{x1:x,x2:x,y1:guideTop,y2:guideBottom,class:'tl-hover-year-line'});append(g,'circle',{cx:x,cy:y,r:radius||4.4,fill:color,class:'tl-paper-dot'});append(g,'title',{},p.year+' - '+p.label+'\n'+p.title);}
  function xForYear(y,margin,innerW,offset){return xForScaleValue(scaleForYear(y),margin,innerW)+(offset||0);}
  function xForScaleValue(v,margin,innerW){const start=scaleForYear(state.yearStart),end=scaleForYear(state.yearEnd,true);return margin.left+((v-start)/Math.max(1e-6,end-start))*innerW;}
  function scaleForYear(year,endEdge){const y=clampYear(year),bin=yearBins.find(b=>y>=b.start&&y<=b.end)||yearBins[yearBins.length-1];if(!bin)return y;const span=Math.max(1,bin.end-bin.start+1),pos=clamp((y-bin.start+(endEdge?1:0))/span*bin.width,0,bin.width);return bin.offset+pos;}
  function visibleYearBins(){const bins=yearBins.filter(bin=>bin.end>=state.yearStart&&bin.start<=state.yearEnd);return bins.length?bins:yearBins;}
  function normalizeYearBins(raw,minY,maxY){const rows=(Array.isArray(raw)?raw:[]).filter(b=>Number.isFinite(parseInt(b.start,10))&&Number.isFinite(parseInt(b.end,10))).map(b=>({label:String(b.label||b.start),start:parseInt(b.start,10),end:parseInt(b.end,10),width:binWidth(b),kind:binKind(b)})).sort((a,b)=>a.start-b.start);const bins=rows.length?rows:[{label:String(minY),start:minY,end:maxY,width:Math.max(1,maxY-minY+1),kind:'one'}];let offset=0;bins.forEach(bin=>{bin.offset=offset;offset+=bin.width;});return bins;}
  function binWidth(row){const width=parseFloat(row&&row.width);if(Number.isFinite(width)&&width>0)return width;const start=parseInt(row&&row.start,10);return Number.isFinite(start)?(start<1950?10:start<2000?5:1):1;}
  function binKind(row){const start=parseInt(row&&row.start,10);return Number.isFinite(start)&&start<1950?'coarse':Number.isFinite(start)&&start<2000?'five':'one';}
  function groupYearCounts(items){const counts=new Map();(items||[]).forEach(p=>{if(!counts.has(p.year))counts.set(p.year,{count:0,items:[]});const row=counts.get(p.year);row.count+=1;row.items.push(p);});return counts;}
  function streamSampleYears(){const years=[];for(let year=state.yearStart;year<=state.yearEnd;year+=1)years.push(year);return years;}
  function streamDensityAtYear(counts,year){let v=0;const bandwidth=2.8;counts.forEach((row,cy)=>{const d=(year-cy)/bandwidth;v+=row.count*Math.exp(-.5*d*d);});return v;}
  function densityStats(groups){const values=[],streamValues=[],years=streamSampleYears();(groups||[]).forEach(g=>{const counts=groupYearCounts(g.papers);counts.forEach(row=>values.push(row.count));years.forEach(year=>{const v=streamDensityAtYear(counts,year);if(v>0)streamValues.push(v);});});if(!values.length)return{min:1,max:1,logMin:Math.log1p(1),logMax:Math.log1p(1),streamMin:1,streamMax:1,streamLogMin:Math.log1p(1),streamLogMax:Math.log1p(1),absLogMax:Math.log1p(128)};const max=Math.max(1,...values),min=Math.max(1,Math.min(...values)),streamMax=Math.max(1,...streamValues),streamMin=Math.max(1,Math.min(...streamValues));return{min:min,max:max,logMin:Math.log1p(min),logMax:Math.log1p(max),streamMin:streamMin,streamMax:streamMax,streamLogMin:Math.log1p(streamMin),streamLogMax:Math.log1p(streamMax),absLogMax:Math.log1p(128)};}
  function scaledDensity(value,stats){return scaledLogDensity(value,stats&&stats.logMin,stats&&stats.logMax,stats&&stats.min,stats&&stats.max,stats&&stats.absLogMax);}
  function scaledStreamDensity(value,stats){return scaledLogDensity(value,stats&&stats.streamLogMin,stats&&stats.streamLogMax,stats&&stats.streamMin,stats&&stats.streamMax,stats&&stats.absLogMax);}
  function scaledLogDensity(value,logMin,logMax,min,max,absLogMax){const v=Math.max(0,value||0);if(v<=0)return 0;const absDenom=Math.max(1e-6,(absLogMax||Math.log1p(128))-Math.log1p(1)),absolute=clamp((Math.log1p(v)-Math.log1p(1))/absDenom,0,1);if(!Number.isFinite(max)||max<=min)return absolute;const relative=clamp((Math.log1p(v)-logMin)/Math.max(1e-6,logMax-logMin),0,1);return clamp(absolute*.35+relative*.65,0,1);}
  function rowHeightForGroup(group,baseRowH,density){const peak=maxYearCount(group.papers),extraMax=state.mode==='super'?104:state.mode==='category'?78:56;return baseRowH+Math.round(extraMax*Math.pow(scaledDensity(peak,density),.74));}
  function densityRadius(count,rowH,topLimit,bottomLimit,density){if(count<2)return 0;const maxRadius=Math.max(0,Math.min(rowH*.28,(bottomLimit-topLimit)/2));return clamp(maxRadius*(.16+.84*Math.pow(scaledDensity(count,density),.78)),5,maxRadius);}
  function dotRadiusForCount(count){return clamp(4.7-Math.log1p(Math.max(1,count))*.35,2.7,4.4);}
  function maxYearCount(items){const counts=groupYearCounts(items);return Math.max(0,...Array.from(counts.values()).map(row=>row.count));}
  function timelineJitter(groupKey,year,paperId){const key=groupKey+'::'+year+'::'+paperId;if(!jitterCache.has(key))jitterCache.set(key,{x:Math.random()*2-1,y:Math.random()*2-1});return jitterCache.get(key);}
  function jitterRangeForYear(year,count,innerW,density){if(count<2)return 0;const bin=yearBins.find(b=>year>=b.start&&year<=b.end),start=scaleForYear(state.yearStart),end=scaleForYear(state.yearEnd,true),pxPerUnit=innerW/Math.max(1e-6,end-start),usable=Math.max(14,(bin?bin.width:1)*pxPerUnit*(.42+.36*scaledDensity(count,density)));return Math.min(42,usable/2);}
  function renderLegend(){const bySuper=new Map();plotted.forEach(p=>{if(p.year<state.yearStart||p.year>state.yearEnd)return;if(state.query&&!matchesQuery(p,state.query))return;bySuper.set(p.superCategory,(bySuper.get(p.superCategory)||0)+1);});const supers=superOrder().filter(s=>bySuper.has(s));Array.from(bySuper.keys()).sort().forEach(s=>{if(!supers.includes(s))supers.push(s);});legend.innerHTML=supers.map(s=>{const active=state.activeSupers.has(s),color=s===UNCATEGORIZED?'#000000':superColor(s);return '<button type="button" class="tl-legend-item'+(active?' is-active':'')+'" data-tl-super="'+escAttr(s)+'" aria-pressed="'+String(active)+'"><span class="tl-legend-swatch" style="--tl-swatch:'+escAttr(color)+'"></span><span>'+esc(s)+'</span><strong>'+(bySuper.get(s)||0)+'</strong></button>';}).join('')||'<p class="tl-empty">No categories in range.</p>';}
  function matchesQuery(p,q){const terms=norm(q).split(/\s+/).filter(Boolean);return terms.every(t=>p.searchText.includes(t));}
  function syncTimelineHeaderHeight(){const header=document.querySelector('.md-header'),h=header?Math.max(0,Math.ceil(header.getBoundingClientRect().height)):0;if(h)document.documentElement.style.setProperty('--tl-header-h',h+'px');}
  function renderStatus(visible,groups){if(status)status.textContent='';const selected=state.selectedId?paperById.get(state.selectedId):null;if(!selected){if(toolbar)toolbar.hidden=true;chip.hidden=true;chip.textContent='';return;}if(toolbar)toolbar.hidden=false;chip.hidden=false;chip.textContent=(selected.year?selected.year+' - ':'')+selected.label;}
  function renderDetail(){const p=state.selectedId?paperById.get(state.selectedId):null;if(!modal||!modalBody||!modalTitle)return;if(!p){modal.hidden=true;modalBody.innerHTML='';modalTitle.textContent='Paper';return;}const title=p.title||p.label||'Untitled',year=p.year||'Undated',summary=p.summary||'No summary recorded yet.',abstract=p.abstract||'No abstract recorded yet.';modalTitle.textContent=title;modalBody.innerHTML='<div class="tl-detail-kicker">'+esc(year)+'</div>'+(p.label&&p.label!==title?'<p class="tl-detail-title">'+esc(p.label)+'</p>':'')+'<div class="tl-modal-section-title">Abstract</div><p class="tl-abstract">'+esc(abstract)+'</p><div class="tl-modal-section-title">Summary</div><p class="tl-summary">'+esc(summary)+'</p><div class="tl-detail-actions paper-link-pills">'+paperActionLink(p.url,'Open Detail Page','internal',false)+paperActionLink(p.contentTreeUrl,'Open in Content Tree','internal',false)+paperActionLink(p.mindMapUrl,'Open in Mind Map','internal',false)+'</div>';modal.hidden=false;}
  function paperActionLink(url,label,variant,external){return url?'<a class="paper-link-pill paper-link-pill--'+escAttr(variant||'internal')+'" href="'+escAttr(url)+'"'+(external?' target="_blank" rel="noopener noreferrer"':'')+'><span class="paper-link-pill__label">'+esc(label)+'</span></a>':'';}
  function nodeColor(cat,sub){if(isUncat(cat))return'#000000';if(sub){const key=cat+'::'+sub;if(!subColorCache.has(key))subColorCache.set(key,hslToHex(subHsl(cat,sub)));return subColorCache.get(key);}if(!colorCache.has(cat))colorCache.set(cat,hslToHex(categoryHsl(cat)));return colorCache.get(cat);}
  function isUncat(cat){return!cat||UNCATEGORIZED_SET.has(cat);}
  function categoryHsl(cat){if(hslCache.has(cat))return hslCache.get(cat);const sup=categorySuper(cat)||cat,base=superHsl(sup),siblings=categoriesForSuper(sup,cat),i=Math.max(siblings.indexOf(cat),0),center=(siblings.length-1)/2,step=siblings.length>1?Math.min(7,18/(siblings.length-1)):0,hsl={h:normHue(base.h+(i-center)*step),s:clamp(base.s+(i%2===0?2:-2),48,86),l:clamp(base.l+(i-center)*2.2,32,58)};hslCache.set(cat,hsl);return hsl;}
  function subHsl(cat,sub){const base=categoryHsl(cat),ordered=(((data.meta||{}).subCategoryOrder||{})[cat]||[]).filter(Boolean),siblings=ordered.includes(sub)?ordered:ordered.concat(sub).sort((a,b)=>a.localeCompare(b)),i=Math.max(siblings.indexOf(sub),0),center=(siblings.length-1)/2,step=siblings.length>1?Math.min(4,14/(siblings.length-1)):0;return{h:normHue(base.h+(i-center)*step),s:clamp(base.s+(i%2===0?3:-3),45,88),l:clamp(base.l+(i-center)*1.5+(i%2===0?1:-1),32,60)};}
  function categorySuper(cat){const explicit=(((data.meta||{}).categorySuperCategory)||{})[cat];if(explicit)return explicit;const p=papers.find(x=>x.category===cat&&x.superCategory);return p?p.superCategory:null;}
  function categoryOrder(){const configured=((data.meta||{}).categoryOrder||[]),cats=new Set(papers.map(p=>p.category).filter(Boolean)),ordered=configured.filter(c=>cats.has(c));Array.from(cats).sort((a,b)=>a.localeCompare(b)).forEach(c=>{if(!ordered.includes(c))ordered.push(c);});return ordered;}
  function superOrder(){const ordered=Array.from(((data.meta||{}).superCategoryOrder||[]));categoryOrder().forEach(c=>{if(isUncat(c))return;const s=categorySuper(c)||c;if(s&&!ordered.includes(s))ordered.push(s);});papers.forEach(p=>{if(p.superCategory&&!ordered.includes(p.superCategory))ordered.push(p.superCategory);});if(!ordered.includes(UNCATEGORIZED))ordered.push(UNCATEGORIZED);return ordered;}
  function superHsl(s){const order=superOrder(),i=Math.max(order.indexOf(s),0),base=PALETTE[i%PALETTE.length],cycle=Math.floor(i/PALETTE.length);return{h:normHue(base.h+cycle*19),s:base.s,l:base.l};}
  function superColor(s){return hslToHex(superHsl(s));}
  function categoriesForSuper(s,current){const siblings=categoryOrder().filter(c=>(categorySuper(c)||c)===s);if(!siblings.includes(current))siblings.push(current);return siblings;}
  function hslToHex(o){const h=o.h/360,s=o.s/100,l=o.l/100,fn=(p,q,t)=>{if(t<0)t+=1;if(t>1)t-=1;if(t<1/6)return p+(q-p)*6*t;if(t<1/2)return q;if(t<2/3)return p+(q-p)*(2/3-t)*6;return p;};let r,g,b;if(s===0){r=g=b=l;}else{const q=l<.5?l*(1+s):l+s-l*s,p=2*l-q;r=fn(p,q,h+1/3);g=fn(p,q,h);b=fn(p,q,h-1/3);}const hex=v=>Math.round(v*255).toString(16).padStart(2,'0');return'#'+hex(r)+hex(g)+hex(b);}
  function compare(a,b){for(let i=0;i<Math.max(a.length,b.length);i++){const d=(a[i]||0)-(b[i]||0);if(d!==0)return d;}return 0;}function positive(i){return i>=0?i:9999;}function clamp(v,min,max){return Math.min(Math.max(v,min),max);}function normHue(h){return((h%360)+360)%360;}function plural(n,s,p){return n+' '+(n===1?s:(p||s+'s'));}function norm(v){return String(v||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'');}
  function readPaperHash(){const hash=window.location.hash.slice(1);if(!hash)return null;const params=new URLSearchParams(hash);return params.get('paper')||params.get('tl');}
  function setHash(id){const url=new URL(window.location.href);url.hash=id?'paper='+encodeURIComponent(id):'';window.history.pushState(null,'',url);}
  function append(parent,tag,attrs,text){const el=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.keys(attrs||{}).forEach(k=>el.setAttribute(k,attrs[k]));if(text!==undefined)el.textContent=text;parent.appendChild(el);return el;}
  function clear(node){while(node.firstChild)node.removeChild(node.firstChild);}
  function esc(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
  function escAttr(v){return esc(v).replace(/`/g,'&#96;');}
  function cssEscape(v){return window.CSS&&typeof window.CSS.escape==='function'?window.CSS.escape(v):String(v).replace(/"/g,'\\"');}
})();
