'use strict';
(function(){
  const app=document.getElementById('tl-app'); if(!app) return;
  const data=window.timelineData;
  if(!data||!Array.isArray(data.papers)||!data.meta){app.innerHTML='<p class="tl-error">Timeline data is unavailable. Run <code>mkdocs build</code> to regenerate it.</p>';return;}
  const UNCATEGORIZED=(data.meta&&data.meta.uncategorizedCategory)||'Uncategorized';
  const UNCATEGORIZED_SET=new Set([UNCATEGORIZED,'Other']);
  const PALETTE=[{h:213,s:76,l:42},{h:152,s:70,l:35},{h:31,s:82,l:43},{h:271,s:62,l:44},{h:334,s:58,l:44},{h:12,s:72,l:42},{h:188,s:72,l:36}];
  const svg=document.getElementById('tl-svg'),svgWrap=document.getElementById('tl-svg-wrap'),status=document.getElementById('tl-status'),legend=document.getElementById('tl-legend'),detail=document.getElementById('tl-detail'),chip=document.getElementById('tl-selection-chip'),form=document.getElementById('tl-search-form'),search=document.getElementById('tl-search'),yearStart=document.getElementById('tl-year-start'),yearEnd=document.getElementById('tl-year-end'),reset=document.getElementById('tl-reset'),dotsToggle=document.getElementById('tl-show-dots'),modeButtons=Array.from(app.querySelectorAll('[data-tl-mode]'));
  const hslCache=new Map(),colorCache=new Map(),subColorCache=new Map(),jitterCache=new Map();
  const papers=data.papers.map(p=>{const y=Number.isInteger(p.year)?p.year:null;const sup=p.superCategory||UNCATEGORIZED;const cat=p.category||UNCATEGORIZED;const sub=p.subCategory||'';return Object.assign({},p,{year:y,superCategory:sup,category:cat,subCategory:sub,searchText:norm([p.label,p.title,p.authorShort,Array.isArray(p.authors)?p.authors.join(' '):'',y||'',sup,cat,sub,Array.isArray(p.tags)?p.tags.join(' '):'',p.summary||''].join(' '))});});
  const paperById=new Map(papers.map(p=>[p.id,p]));
  const plotted=papers.filter(p=>Number.isInteger(p.year));
  const minYear=data.meta.minYear||Math.min(...plotted.map(p=>p.year)),maxYear=data.meta.maxYear||Math.max(...plotted.map(p=>p.year)),yearBins=normalizeYearBins((data.meta||{}).yearBins,minYear,maxYear),defaultStartYear=minYear;
  const state={mode:'category',activeSuper:null,query:'',selectedId:null,yearStart:defaultStartYear,yearEnd:maxYear,showDots:true};
  const hashId=readPaperHash(); if(hashId&&paperById.has(hashId)) state.selectedId=hashId;
  yearStart.value=state.yearStart; yearEnd.value=state.yearEnd; dotsToggle.checked=state.showDots;
  form.addEventListener('submit',e=>{e.preventDefault();const first=filtered()[0];if(first) selectPaper(first.id,true);});
  search.addEventListener('input',()=>{state.query=search.value.trim();render();});
  yearStart.addEventListener('change',syncYears); yearEnd.addEventListener('change',syncYears);
  dotsToggle.addEventListener('change',()=>{state.showDots=dotsToggle.checked;render();});
  reset.addEventListener('click',()=>{state.mode='category';state.activeSuper=null;state.query='';state.selectedId=null;state.yearStart=defaultStartYear;state.yearEnd=maxYear;state.showDots=true;search.value='';yearStart.value=defaultStartYear;yearEnd.value=maxYear;dotsToggle.checked=true;setHash(null);render();});
  modeButtons.forEach(button=>button.addEventListener('click',()=>{state.mode=button.getAttribute('data-tl-mode')||'category';render();}));
  legend.addEventListener('click',e=>{const button=e.target.closest('[data-tl-super]');if(!button)return;const next=button.getAttribute('data-tl-super');state.activeSuper=state.activeSuper===next?null:next;render();});
  svg.addEventListener('click',e=>{const target=e.target.closest('[data-paper-id]');if(target) selectPaper(target.getAttribute('data-paper-id'),true);});
  svg.addEventListener('keydown',e=>{if(e.key!=='Enter'&&e.key!==' ')return;const target=e.target.closest('[data-paper-id]');if(!target)return;e.preventDefault();selectPaper(target.getAttribute('data-paper-id'),true);});
  window.addEventListener('popstate',()=>{const next=readPaperHash();state.selectedId=next&&paperById.has(next)?next:null;render();});
  if(window.ResizeObserver){let pending=false;new ResizeObserver(()=>{if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;render();});}).observe(svgWrap);}else{window.addEventListener('resize',render);}
  render();
  function syncYears(){const a=clampYear(parseInt(yearStart.value,10)),b=clampYear(parseInt(yearEnd.value,10));state.yearStart=Math.min(a,b);state.yearEnd=Math.max(a,b);yearStart.value=state.yearStart;yearEnd.value=state.yearEnd;render();}
  function clampYear(v){return Number.isFinite(v)?Math.min(Math.max(v,minYear),maxYear):minYear;}
  function selectPaper(id,push){if(!paperById.has(id))return;state.selectedId=id;if(push)setHash(id);render();const node=svg.querySelector('[data-paper-id="'+cssEscape(id)+'"]');if(node&&node.focus)node.focus({preventScroll:true});}
  function render(){const visible=filtered(),groups=buildGroups(visible);renderLegend();renderSvg(groups);renderStatus(visible,groups);renderDetail();modeButtons.forEach(b=>b.setAttribute('aria-pressed',String(b.getAttribute('data-tl-mode')===state.mode)));}
  function filtered(){const terms=norm(state.query).split(/\s+/).filter(Boolean);return plotted.filter(p=>p.year>=state.yearStart&&p.year<=state.yearEnd&&(!state.activeSuper||p.superCategory===state.activeSuper)&&(!terms.length||terms.every(t=>p.searchText.includes(t))));}
  function buildGroups(visible){const map=new Map();visible.forEach(p=>{const d=groupDescriptor(p);if(!map.has(d.key))map.set(d.key,Object.assign({},d,{superCategory:p.superCategory,category:p.category,subCategory:p.subCategory,papers:[]}));map.get(d.key).papers.push(p);});return Array.from(map.values()).sort((a,b)=>compare(a.sort,b.sort)||a.label.localeCompare(b.label));}
  function groupDescriptor(p){const si=positive(superOrder().indexOf(p.superCategory)),ci=positive(categoryOrder().indexOf(p.category)),subs=((data.meta||{}).subCategoryOrder||{})[p.category]||[],subi=positive(p.subCategory?subs.indexOf(p.subCategory):-1);if(state.mode==='super')return{key:'super:'+p.superCategory,label:p.superCategory,pathLabel:p.superCategory,color:isUncat(p.category)?'#000000':superColor(p.superCategory),sort:[si,0,0]};if(state.mode==='sub'){const label=p.subCategory||p.category;return{key:'sub:'+p.category+'::'+(p.subCategory||'(direct)'),label:label,pathLabel:p.subCategory?p.category+' / '+p.subCategory:p.category,color:nodeColor(p.category,p.subCategory),sort:[si,ci,subi]};}return{key:'category:'+p.category,label:p.category,pathLabel:p.superCategory+' / '+p.category,color:nodeColor(p.category,''),sort:[si,ci,0]};}
  function renderSvg(groups){clear(svg);const wrapWidth=svgWrap?svgWrap.clientWidth:0,parentWidth=svg.parentElement?svg.parentElement.clientWidth:0,available=Math.max(320,Math.floor(wrapWidth||parentWidth||960)),compact=available<760,topLabels=available<680,margin={top:topLabels?54:44,right:compact?24:48,bottom:52,left:topLabels?24:(compact?204:282)},baseRowH=state.mode==='sub'?(compact?62:68):state.mode==='super'?(compact?84:92):(compact?70:78),rows=groups.map(g=>({group:g,rowH:baseRowH+Math.min(72,Math.max(0,maxYearCount(g.papers)-4)*4)})),innerW=Math.max(180,available-margin.left-margin.right),width=margin.left+innerW+margin.right,height=Math.max(420,margin.top+rows.reduce((sum,r)=>sum+r.rowH,0)+margin.bottom),bottom=height-margin.bottom;svg.setAttribute('viewBox','0 0 '+width+' '+height);svg.setAttribute('width','100%');svg.setAttribute('height',height);append(svg,'rect',{x:0,y:0,width:width,height:height,class:'tl-svg-bg'});drawGrid(svg,margin,width,bottom);if(!groups.length){append(svg,'text',{x:margin.left,y:margin.top+70,class:'tl-empty-svg'},'No dated papers match the current filters.');return;}let top=margin.top;rows.forEach(row=>{const center=topLabels?top+Math.max(56,row.rowH*.64):top+row.rowH/2;drawGroup(svg,row.group,top,center,row.rowH,margin,innerW,topLabels);top+=row.rowH;});const selected=state.selectedId?paperById.get(state.selectedId):null;if(selected&&Number.isInteger(selected.year)){const x=xForYear(selected.year,margin,innerW);append(svg,'line',{x1:x,x2:x,y1:margin.top-14,y2:bottom,class:'tl-selected-year-line'});}}
  function drawGrid(root,margin,width,bottom){const innerW=width-margin.left-margin.right,g=append(root,'g',{class:'tl-grid'}),bins=visibleYearBins();responsiveYearTicks(yearBoundaryTicks(bins),margin,innerW).forEach(tick=>{const x=xForScaleValue(tick.value,margin,innerW),major=tick.kind!=='one'||tick.year%5===0,label=String(tick.year);append(g,'line',{x1:x,x2:x,y1:margin.top-18,y2:bottom,class:major?'tl-grid-major':'tl-grid-minor'});append(g,'text',{x:x,y:margin.top-24,class:'tl-year-label'},label);append(g,'text',{x:x,y:bottom+30,class:'tl-year-label'},label);});append(g,'line',{x1:margin.left,x2:width-margin.right,y1:margin.top-6,y2:margin.top-6,class:'tl-axis-line'});append(g,'line',{x1:margin.left,x2:width-margin.right,y1:bottom+8,y2:bottom+8,class:'tl-axis-line'});}
  function yearBoundaryTicks(bins){if(!bins.length)return[];const ticks=[];bins.forEach((bin,i)=>{const leftYear=Math.max(bin.start,state.yearStart),next=bins[i+1];if(i===0||leftYear>ticks[ticks.length-1].year)ticks.push({year:leftYear,value:scaleForYear(leftYear),kind:bin.kind});if(next){const rightYear=Math.max(next.start,state.yearStart);ticks.push({year:rightYear,value:next.offset,kind:next.kind});}else{const rightYear=Math.min(bin.end,state.yearEnd);if(rightYear>ticks[ticks.length-1].year)ticks.push({year:rightYear,value:scaleForYear(rightYear,true),kind:bin.kind});}});return ticks.filter((tick,i,rows)=>i===0||tick.year!==rows[i-1].year||Math.abs(tick.value-rows[i-1].value)>1e-6);}
  function responsiveYearTicks(ticks,margin,innerW){if(ticks.length<2)return ticks;const minGap=42,withX=ticks.map(t=>Object.assign({x:xForScaleValue(t.value,margin,innerW),region:tickRegion(t.year)},t)),selected=[];['coarse','five','one'].forEach(region=>{const rows=withX.filter(t=>t.region===region);if(!rows.length)return;const gaps=rows.slice(1).map((t,i)=>t.x-rows[i].x).filter(g=>g>0),baseGap=gaps.length?Math.min(...gaps):innerW,step=Math.max(1,Math.ceil(minGap/baseGap));rows.forEach((tick,i)=>{if(i%step===0||i===rows.length-1)selected.push(tick);});});return withoutTickCollisions(selected.sort((a,b)=>a.x-b.x),minGap);}
  function withoutTickCollisions(ticks,minGap){let lastX=-Infinity;return ticks.filter(tick=>{if(tick.x-lastX<minGap)return false;lastX=tick.x;return true;});}
  function tickRegion(year){return year<1950?'coarse':year<2000?'five':'one';}
  function drawGroup(root,group,top,center,rowH,margin,innerW,topLabels){const lane=append(root,'g',{class:'tl-group','data-group-key':group.key}),labelMax=topLabels?Math.max(72,innerW-90):Math.max(44,margin.left-60);append(lane,'line',{x1:margin.left,x2:margin.left+innerW,y1:center,y2:center,class:'tl-lane-line'});if(topLabels){append(lane,'rect',{x:margin.left,y:top+6,width:innerW,height:34,rx:8,class:'tl-group-label-bg'});append(lane,'circle',{cx:margin.left+12,cy:top+23,r:5,fill:group.color,class:'tl-group-swatch'});fitSvgText(append(lane,'text',{x:margin.left+26,y:top+20,class:'tl-group-label'},group.label),group.label,labelMax);append(lane,'text',{x:margin.left+26,y:top+34,class:'tl-group-meta'},plural(group.papers.length,'paper'));}else{append(lane,'rect',{x:0,y:top+4,width:margin.left-18,height:rowH-8,rx:8,class:'tl-group-label-bg'});append(lane,'circle',{cx:18,cy:center,r:5,fill:group.color,class:'tl-group-swatch'});fitSvgText(append(lane,'text',{x:32,y:center-3,class:'tl-group-label'},group.label),group.label,labelMax);append(lane,'text',{x:32,y:center+14,class:'tl-group-meta'},plural(group.papers.length,'paper'));}append(lane,'path',{d:streamPath(group,center,rowH,margin,innerW),fill:group.color,stroke:group.color,class:'tl-stream'});if(!state.showDots)return;const byYear=new Map();group.papers.forEach(p=>{if(!byYear.has(p.year))byYear.set(p.year,[]);byYear.get(p.year).push(p);});Array.from(byYear.keys()).sort((a,b)=>a-b).forEach(year=>{const items=byYear.get(year).sort((a,b)=>a.label.localeCompare(b.label)),range=jitterRangeForYear(year,items.length,innerW),topLimit=top+(topLabels?44:14),bottomLimit=top+rowH-14,yRadius=items.length<2?0:Math.max(0,Math.min(rowH*.34,(bottomLimit-topLimit)/2));items.forEach(p=>{const jitter=timelineJitter(group.key,year,p.id),x=xForYear(year,margin,innerW,jitter.x*range),y=clamp(center+jitter.y*yRadius,topLimit,bottomLimit);drawPaper(lane,p,x,y,group.color);});});}
  function fitSvgText(el,text,maxWidth){const value=String(text||'');el.textContent=value;if(!value||safeTextLength(el)<=maxWidth)return;const suffix='...';let lo=0,hi=value.length,best=suffix;while(lo<=hi){const mid=Math.floor((lo+hi)/2),next=value.slice(0,mid).trimEnd()+suffix;el.textContent=next;if(safeTextLength(el)<=maxWidth){best=next;lo=mid+1;}else{hi=mid-1;}}el.textContent=best;}
  function safeTextLength(el){return typeof el.getComputedTextLength==='function'?el.getComputedTextLength():el.textContent.length*7;}
  function streamPath(group,center,rowH,margin,innerW){const counts=new Map();group.papers.forEach(p=>counts.set(p.year,(counts.get(p.year)||0)+1));const bins=visibleYearBins(),samples=[];bins.forEach(bin=>{let v=0;counts.forEach((c,cy)=>{const d=(scaleForYear(cy)-bin.offset)/Math.max(1.1,bin.width*1.15);v+=c*Math.exp(-.5*d*d);});const h=clamp(3+Math.log1p(v)*10.5,3.2,rowH/2-10);samples.push({x:xForScaleValue(bin.offset+bin.width/2,margin,innerW),top:center-h,bottom:center+h});});if(!samples.length)samples.push({x:margin.left,top:center-3,bottom:center+3});return 'M '+samples.map(p=>p.x.toFixed(1)+' '+p.top.toFixed(1)).join(' L ')+' L '+samples.slice().reverse().map(p=>p.x.toFixed(1)+' '+p.bottom.toFixed(1)).join(' L ')+' Z';}
  function drawPaper(root,p,x,y,color){const selected=p.id===state.selectedId,g=append(root,'g',{class:'tl-paper-node'+(selected?' is-selected':''),'data-paper-id':p.id,tabindex:0,role:'button','aria-label':p.label+', '+p.year});append(g,'circle',{cx:x,cy:y,r:selected?6.8:4.4,fill:color,class:'tl-paper-dot'});append(g,'title',{},p.year+' - '+p.label+'\n'+p.title);if(selected)append(g,'text',{x:x+10,y:y-9,class:'tl-selected-label'},p.label);}
  function xForYear(y,margin,innerW,offset){return xForScaleValue(scaleForYear(y),margin,innerW)+(offset||0);}
  function xForScaleValue(v,margin,innerW){const start=scaleForYear(state.yearStart),end=scaleForYear(state.yearEnd,true);return margin.left+((v-start)/Math.max(1e-6,end-start))*innerW;}
  function scaleForYear(year,endEdge){const y=clampYear(year),bin=yearBins.find(b=>y>=b.start&&y<=b.end)||yearBins[yearBins.length-1];if(!bin)return y;const span=Math.max(1,bin.end-bin.start+(endEdge?0:1));const pos=endEdge&&y===bin.end?bin.width:((y-bin.start)/span)*bin.width;return bin.offset+pos;}
  function visibleYearBins(){const bins=yearBins.filter(bin=>bin.end>=state.yearStart&&bin.start<=state.yearEnd);return bins.length?bins:yearBins;}
  function normalizeYearBins(raw,minY,maxY){const rows=(Array.isArray(raw)?raw:[]).filter(b=>Number.isFinite(parseInt(b.start,10))&&Number.isFinite(parseInt(b.end,10))).map(b=>({label:String(b.label||b.start),start:parseInt(b.start,10),end:parseInt(b.end,10),width:binWidth(b),kind:binKind(b)})).sort((a,b)=>a.start-b.start);const bins=rows.length?rows:[{label:String(minY),start:minY,end:maxY,width:Math.max(1,maxY-minY+1),kind:'one'}];let offset=0;bins.forEach(bin=>{bin.offset=offset;offset+=bin.width;});return bins;}
  function binWidth(row){const width=parseFloat(row&&row.width);if(Number.isFinite(width)&&width>0)return width;const start=parseInt(row&&row.start,10);return Number.isFinite(start)?(start<1950?10:start<2000?5:1):1;}
  function binKind(row){const start=parseInt(row&&row.start,10);return Number.isFinite(start)&&start<1950?'coarse':Number.isFinite(start)&&start<2000?'five':'one';}
  function maxYearCount(items){const counts=new Map();(items||[]).forEach(p=>counts.set(p.year,(counts.get(p.year)||0)+1));return Math.max(0,...counts.values());}
  function timelineJitter(groupKey,year,paperId){const key=groupKey+'::'+year+'::'+paperId;if(!jitterCache.has(key))jitterCache.set(key,{x:Math.random()*2-1,y:Math.random()*2-1});return jitterCache.get(key);}
  function jitterRangeForYear(year,count,innerW){if(count<2)return 0;const bin=yearBins.find(b=>year>=b.start&&year<=b.end),start=scaleForYear(state.yearStart),end=scaleForYear(state.yearEnd,true),pxPerUnit=innerW/Math.max(1e-6,end-start),usable=Math.max(14,(bin?bin.width:1)*pxPerUnit*.74);return Math.min(28,usable/2);}
  function renderLegend(){const bySuper=new Map();plotted.forEach(p=>{if(p.year<state.yearStart||p.year>state.yearEnd)return;if(state.query&&!matchesQuery(p,state.query))return;bySuper.set(p.superCategory,(bySuper.get(p.superCategory)||0)+1);});const supers=superOrder().filter(s=>bySuper.has(s));Array.from(bySuper.keys()).sort().forEach(s=>{if(!supers.includes(s))supers.push(s);});legend.innerHTML=supers.map(s=>{const active=state.activeSuper===s,color=s===UNCATEGORIZED?'#000000':superColor(s);return '<button type="button" class="tl-legend-item'+(active?' is-active':'')+'" data-tl-super="'+escAttr(s)+'"><span class="tl-legend-swatch" style="--tl-swatch:'+escAttr(color)+'"></span><span>'+esc(s)+'</span><strong>'+(bySuper.get(s)||0)+'</strong></button>';}).join('')||'<p class="tl-empty">No categories in range.</p>';}
  function matchesQuery(p,q){const terms=norm(q).split(/\s+/).filter(Boolean);return terms.every(t=>p.searchText.includes(t));}
  function renderStatus(visible,groups){const label=state.mode==='super'?'super-category stream':state.mode==='sub'?'sub-category stream':'category stream';status.textContent=plural(visible.length,'paper')+' across '+plural(groups.length,label)+(state.showDots?'':' - dots hidden');const selected=state.selectedId?paperById.get(state.selectedId):null;if(!selected){chip.hidden=true;chip.textContent='';return;}chip.hidden=false;chip.textContent=(selected.year?selected.year+' - ':'')+selected.label;}
  function renderDetail(){const p=state.selectedId?paperById.get(state.selectedId):null;if(!p){detail.innerHTML='<h2>Select a Paper</h2><p>Click a point in the stream or search for a title to inspect the paper, jump to its generated page, or open it in the Mind Map.</p><p>The current view runs from <strong>'+esc(state.yearStart)+'</strong> to <strong>'+esc(state.yearEnd)+'</strong>.</p>';return;}const tags=Array.isArray(p.tags)&&p.tags.length?'<div class="tl-tags">'+p.tags.slice(0,12).map(t=>'<span>'+esc(t)+'</span>').join('')+'</div>':'';const authors=Array.isArray(p.authors)&&p.authors.length?p.authors.slice(0,8).join(', ')+(p.authors.length>8?', ...':''):'No authors recorded';const path=Array.isArray(p.path)?p.path.filter(Boolean).join(' / '):[p.superCategory,p.category,p.subCategory].filter(Boolean).join(' / ');detail.innerHTML='<div class="tl-detail-kicker">'+esc(p.year||'Undated')+'</div><h2>'+esc(p.label||p.title||'Untitled')+'</h2>'+(p.title&&p.title!==p.label?'<p class="tl-detail-title">'+esc(p.title)+'</p>':'')+'<dl><div><dt>Authors</dt><dd>'+esc(authors)+'</dd></div>'+(p.source?'<div><dt>Source</dt><dd>'+esc(p.source)+'</dd></div>':'')+'<div><dt>Path</dt><dd>'+esc(path)+'</dd></div></dl>'+(p.summary?'<p class="tl-summary">'+esc(p.summary)+'</p>':'')+tags+'<div class="tl-detail-actions"><a href="'+escAttr(p.url)+'">Open paper</a><a href="'+escAttr(p.mindMapUrl)+'">Open in Mind Map</a></div>';}
  function nodeColor(cat,sub){if(isUncat(cat))return'#000000';if(sub){const key=cat+'::'+sub;if(!subColorCache.has(key))subColorCache.set(key,hslToHex(subHsl(cat,sub)));return subColorCache.get(key);}if(!colorCache.has(cat))colorCache.set(cat,hslToHex(categoryHsl(cat)));return colorCache.get(cat);}
  function isUncat(cat){return!cat||UNCATEGORIZED_SET.has(cat);}
  function categoryHsl(cat){if(hslCache.has(cat))return hslCache.get(cat);const sup=categorySuper(cat)||cat,base=superHsl(sup),siblings=categoriesForSuper(sup,cat),i=Math.max(siblings.indexOf(cat),0),center=(siblings.length-1)/2,step=siblings.length>1?Math.min(7,18/(siblings.length-1)):0,hsl={h:normHue(base.h+(i-center)*step),s:clamp(base.s+(i%2===0?2:-2),48,86),l:clamp(base.l+(i-center)*2.2,32,58)};hslCache.set(cat,hsl);return hsl;}
  function subHsl(cat,sub){const base=categoryHsl(cat),ordered=(((data.meta||{}).subCategoryOrder||{})[cat]||[]).filter(Boolean),siblings=ordered.includes(sub)?ordered:ordered.concat(sub).sort((a,b)=>a.localeCompare(b)),i=Math.max(siblings.indexOf(sub),0),center=(siblings.length-1)/2,step=siblings.length>1?Math.min(4,14/(siblings.length-1)):0;return{h:normHue(base.h+(i-center)*step),s:clamp(base.s+(i%2===0?3:-3),45,88),l:clamp(base.l+(i-center)*1.5+(i%2===0?1:-1),32,60)};}
  function categorySuper(cat){const explicit=(((data.meta||{}).categorySuperCategory)||{})[cat];if(explicit)return explicit;const p=papers.find(x=>x.category===cat&&x.superCategory);return p?p.superCategory:null;}
  function categoryOrder(){const configured=((data.meta||{}).categoryOrder||[]),cats=new Set(papers.map(p=>p.category).filter(Boolean)),ordered=configured.filter(c=>cats.has(c));Array.from(cats).sort((a,b)=>a.localeCompare(b)).forEach(c=>{if(!ordered.includes(c))ordered.push(c);});return ordered;}
  function superOrder(){const ordered=Array.from(((data.meta||{}).superCategoryOrder||[]));categoryOrder().forEach(c=>{if(isUncat(c))return;const s=categorySuper(c)||c;if(s&&!ordered.includes(s))ordered.push(s);});papers.forEach(p=>{if(p.superCategory&&!ordered.includes(p.superCategory))ordered.push(p.superCategory);});if(!ordered.includes(UNCATEGORIZED))ordered.push(UNCATEGORIZED);return ordered;}
  function superHsl(s){const order=superOrder(),i=Math.max(order.indexOf(s),0),base=PALETTE[i%PALETTE.length],cycle=Math.floor(i/PALETTE.length);return{h:normHue(base.h+cycle*19),s:base.s,l:base.l};}
  function superColor(s){return hslToHex(superHsl(s));}
  function categoriesForSuper(s,current){const siblings=categoryOrder().filter(c=>(categorySuper(c)||c)===s);if(!siblings.includes(current))siblings.push(current);return siblings;}
  function hslToHex(o){const h=o.h/360,s=o.s/100,l=o.l/100,fn=(p,q,t)=>{if(t<0)t+=1;if(t>1)t-=1;if(t<1/6)return p+(q-p)*6*t;if(t<1/2)return q;if(t<2/3)return p+(q-p)*(2/3-t)*6;return p;};let r,g,b;if(s===0){r=g=b=l;}else{const q=l<.5?l*(1+s):l+s-l*s,p=2*l-q;r=fn(p,q,h+1/3);g=fn(p,q,h);b=fn(p,q,h-1/3);}const hex=v=>Math.round(v*255).toString(16).padStart(2,'0');return'#'+hex(r)+hex(g)+hex(b);}
  function compare(a,b){for(let i=0;i<Math.max(a.length,b.length);i++){const d=(a[i]||0)-(b[i]||0);if(d!==0)return d;}return 0;}function positive(i){return i>=0?i:9999;}function clamp(v,min,max){return Math.min(Math.max(v,min),max);}function normHue(h){return((h%360)+360)%360;}function plural(n,s,p){return n+' '+(n===1?s:(p||s+'s'));}function norm(v){return String(v||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'');}
  function readPaperHash(){const hash=window.location.hash.slice(1);if(!hash)return null;const params=new URLSearchParams(hash);return params.get('paper')||params.get('tl');}
  function setHash(id){const url=new URL(window.location.href);url.hash=id?'paper='+encodeURIComponent(id):'';window.history.pushState(null,'',url);}
  function append(parent,tag,attrs,text){const el=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.keys(attrs||{}).forEach(k=>el.setAttribute(k,attrs[k]));if(text!==undefined)el.textContent=text;parent.appendChild(el);return el;}
  function clear(node){while(node.firstChild)node.removeChild(node.firstChild);}
  function esc(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
  function escAttr(v){return esc(v).replace(/`/g,'&#96;');}
  function cssEscape(v){return window.CSS&&typeof window.CSS.escape==='function'?window.CSS.escape(v):String(v).replace(/"/g,'\\"');}
})();
