"""Paths and headers for normalization database generation."""

from knowledge_base.config import KB_DIR

METADATA_ROOT = KB_DIR / "docs" / "papers"
NORMALIZATION_DIR = KB_DIR / "normalization"
AUTHORS_DB = NORMALIZATION_DIR / "authors.yml"
SOURCES_DB = NORMALIZATION_DIR / "sources.yml"
TAGS_DB = NORMALIZATION_DIR / "tags.yml"

AUTHORS_HEADER = """# Author normalization database.
# Canonical author names should use ASCII, full first name, middle initial(s)
# when known, and full last name. Add observed variants under aliases.
# Generated by scripts/build_normalization_db.py; edit by hand as needed."""

SOURCES_HEADER = """# Source/venue normalization database.
# Canonical sources should use the preferred venue name without publication
# years. Add abbreviations or alternate spellings under aliases.
# Generated by scripts/build_normalization_db.py; edit by hand as needed."""

TAGS_HEADER = """# Tag normalization database.
# Canonical tags should use full spelling instead of acronyms. Add observed
# variants, abbreviations, plural/singular forms, and casing variants under aliases.
# Generated by scripts/build_normalization_db.py; edit by hand as needed."""
