site_name: Knowledge Base

site_url: https://bengravell.github.io/knowledge-base/

plugins:
  - search
  - macros
  - gen-files:
      scripts:
        - generate_papers.py

theme:
  name: material
  logo: icon.png   
  favicon: favicon.png

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  
  font:
    text: Atkinson Hyperlegible Next
    code: Atkinson Hyperlegible Mono

  features:
    - navigation.expand
    - navigation.sections
    - content.code.annotate
    - content.tabs.link
    - metadata
    - tags
    - search.highlight

markdown_extensions:
  - meta
  - admonition
  - footnotes
  - pymdownx.superfences
  - pymdownx.snippets
  - attr_list
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Planning:
    - Path Planning:
      - Geometric Planning:
        - Rapidly Exploring Random Trees (RRT):
          - RRT: papers/1998_lavalle_rapidly_exploring_random_trees.md
          - RRT-Connect: papers/2000_kuffner_rrt_connect_an_efficient.md
          - EET: papers/2008_rickert_balancing_exploration_and_exploitation.md
          - RRT*: papers/1105_1186.md
          - Anytime RRT*: papers/2011_karaman_anytime_motion_planning_using.md
          - RRT* theory correction: papers/1909_09688.md
          - RRT#: papers/1204_6453.md
          - FMT*: papers/1306_3532.md
          - Informed RRT*: papers/1404_2334.md
          - BIT*: papers/1405_5848.md
      - Path Generation:
        - Dubins path: papers/1957_dubins_on_curves_of_minimal.md
        - Reeds-Shepp path: papers/1990_reeds_optimal_paths_for_a.md
      - Path Optimization:
        - TODO
    - Trajectory Planning:
      - Kinodynamic Planning:
        - Rapidly Exploring Random Trees (RRT):
          - Kinodynamic RRT: papers/1999_lavalle_randomized_kinodynamic_planning.md
      - Trajectory Generation:
        - TODO
      - Trajectory Optimization:
        - TODO
    - Speed Planning:
      - TODO
    - Interaction-aware Planning:
      - Multimodal Probabilistic Model-Based Planning for Human-Robot Interaction: papers/1710_09483.md
  - Prediction:
    - Real-Time Learning of Predictive Dynamic Obstacle Models for Robotic Motion Planning: papers/2511_00814.md
  - Control:
    - Proportional-integral-derivative (PID):
      - TODO
    - Pole placement:
      - TODO  
    - Linear Quadratic Regulator (LQR):
      - TODO
    - Model Preditive Control (MPC):
      - TODO
    - Robust Control:
      - Robustness margins for LQG: papers/1978_doyle_guaranteed_margins_for_lqg.md
  - Reinforcement Learning:
    - TODO
  - Optimization:
    - Automatic Generation of Explicit Quadratic Programming Solvers: papers/2506_11513.md
  - Machine Learning:
    - Vision-language-action (VLA) Models:
      - Alpamayo-R1: papers/2511_00088.md
    - Large language models (LLM):
      - Transformers & Attention-based models:
        - Attention Is All You Need: papers/1706_03762.md
  - Just for Fun:
    - Design and Control of a Bipedal Robotic Character: papers/2501_05204.md