site_name: Knowledge Base

site_url: https://bengravell.github.io/knowledge-base/

plugins:
  - search
  - macros
  - gen-files:
      scripts:
        - generate_papers.py

theme:
  name: material
  logo: icon.png   
  favicon: favicon.png

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  
  font:
    text: Atkinson Hyperlegible Next
    code: Atkinson Hyperlegible Mono

  features:
    - navigation.expand
    - navigation.sections
    - content.code.annotate
    - content.tabs.link
    - metadata
    - tags
    - search.highlight

markdown_extensions:
  - meta
  - admonition
  - footnotes
  - pymdownx.superfences
  - pymdownx.snippets
  - attr_list
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Planning:
    - Path Planning:
      - Geometric Planning:
        - Probabilistic Roadmap (PRM):
          - PRM: papers/1996_kavraki_probabilistic_roadmaps_for_path.md
          - PRM*: papers/1105_1186.md
        - Rapidly Exploring Random Trees (RRT):
          - RRT: papers/1998_lavalle_rapidly_exploring_random_trees.md
          - RRT-Connect: papers/2000_kuffner_rrt_connect_an_efficient.md
          - EET: papers/2008_rickert_balancing_exploration_and_exploitation.md
          - RRT*: papers/1105_1186.md
          - Anytime RRT*: papers/2011_karaman_anytime_motion_planning_using.md
          - RRT* theory correction: papers/1909_09688.md
          - RRT*-Connect: papers/2015_klemm_rrt_star_connect_faster.md
          - RRT#: papers/1204_6453.md
          - FMT*: papers/1306_3532.md
          - Informed RRT*: papers/1404_2334.md
          - BIT*: papers/1405_5848.md
          - RABIT*: papers/2016_choudhury_regionally_accelerated_batch_informed.md
          - Informed RRT*-Connect: papers/2020_mashayekhi_informed_rrt_star_connect.md
          - Sliding Window Informed RRT*: papers/2021_li_sliding_window_informed_rrt.md
          - FCIT*: papers/2411_17902.md
          - Spline-based RRT: papers/2013_yang_spline_based_rrt_path.md
          - Continuous-Curvature Target Tree: papers/2201_03163.md
          - FDSPC: papers/2405_03281.md
        - GPU Parallelized Planning:
          - GMT*: papers/1705_02403.md
          - Kino-PAX: papers/2409_06807.md
          - Kino-PAX+: papers/2602_02846.md
          - pRRTC: papers/2503_06757.md
          - cuRobo: papers/2310_17274.md
          - cuTAMP: papers/2411_11833.md
        - Dynamic Replanning:
          - RRTX: papers/2015_otte_rrtx_asymptotically_optimal_single.md
          - RT-FMT: papers/2502_09556.md
      - Path Generation:
        - Lines & Arcs:
          - Dubins path: papers/1957_dubins_on_curves_of_minimal.md
          - Reeds-Shepp path: papers/1990_reeds_optimal_paths_for_a.md
        - Clothoids (linear curvature):
          - SCC path: papers/1997_scheuer_continuous_curvature_path_planning.md
          - CC Steer: papesr/2004_fraichard_from_reeds_and_shepps\metadata.yml.md
        - Generalized Clothoids (nonlinear curvature):
          - Cubic Curvature Polynomials: papers/2001_nagy_trajectory_generation_for_car.md
          - Sharpness Continuous path: papers/1801_08995.md
        - Polynomials & Splines:
          - Quintic G2 Splines: papers/2000_piazzi_quintic_g2_splines_for.md
      - Path Optimization:
        - TODO
    - Trajectory Planning:
      - Kinodynamic Planning:
        - Rapidly Exploring Random Trees (RRT):
          - Kinodynamic RRT: papers/1999_lavalle_randomized_kinodynamic_planning.md
          - Kinodynamic RRT*: papers/2010_karaman_optimal_kinodynamic_motion_planning.md
          - Linear Kinodynamic RRT*: papers/1205_5088.md
          - LQR-RRT*: papers/2012_perez_lqr_rrt_star_optimal.md
          - RRT*_MotionPrimitives: papers/1809_02399.md
          - BB-RRT: papers/2210_01744.md
          - iDb-RRT: papers/2403_10745.md
          - AkinoPDF: papers/2603_16059.md
          - Completeness of Randomized Kinodynamic Planners with State-based Steering: papers/1511_05259.md
        - Expansive Space Trees (EST):
          - EST: TODO
        - Stable Sparse Tree (SST):
          - SST*: papers/1407_2896.md
        - Meta Algorithms:
          - AO-x: papers/1505_04098.md
          - AORRTC: papers/2505_10542.md
        - Planning with Graphs of Convex Sets (GCS):
          - Shortest Paths in Graphs of Convex Sets: papers/2101_11565.md
          - Motion Planning around Obstacles with Convex Optimization: papers/2205_04422.md
          - Fast Path Planning Through Large Collections of Safe Boxes: papers/2305_01072.md
          - A Biconvex Method for Minimum-time Motion Planning Through Sequences of Convex Sets: papers/2504_18978.md
      - Trajectory Generation:
        - TODO
      - Trajectory Optimization:
        - Model Predictive Sampling-Based Control:
          - Judo: papers/2506_17184.md
    - Speed Planning:
      - Time-Optimal Path Parameterization (TOPP):
        - TOPP: papers/1985_bobrow_time_optimal_control_of.md
        - AVP: papers/1411_4045.md
        - TOPP-RA: papers/1707_07239.md
    - Interaction-aware Planning:
      - Multimodal Probabilistic Model-Based Planning for Human-Robot Interaction: papers/1710_09483.md
      - VISTA 2.0: papers/2111_12083.md
      - Learning Interactive Driving Policies via Data-driven Simulation: papers/2111_12137.md
    - Machine Learning in Motion Planning:
      - RRT-CoLearn: papers/1710_10122.md
      - PRESTO: papers/2409_16012.md
  - Prediction:
    - Real-Time Learning of Predictive Dynamic Obstacle Models for Robotic Motion Planning: papers/2511_00814.md
  - Control:
    - Proportional-integral-derivative (PID):
      - TODO
    - Pole placement:
      - TODO  
    - Linear Quadratic Regulator (LQR):
      - TODO
    - Model Preditive Control (MPC):
      - TODO
    - Robust Control:
      - Robustness margins for LQG: papers/1978_doyle_guaranteed_margins_for_lqg.md
  - Reinforcement Learning:
    - TODO
  - Optimization:
    - Automatic Generation of Explicit Quadratic Programming Solvers: papers/2506_11513.md
  - Machine Learning:
    - Vision-language-action (VLA) Models:
      - Alpamayo-R1: papers/2511_00088.md
    - Large language models (LLM):
      - Transformers & Attention-based models:
        - Attention Is All You Need: papers/1706_03762.md
  - Just for Fun:
    - Design and Control of a Bipedal Robotic Character: papers/2501_05204.md