site_name: Knowledge Base

site_url: https://bengravell.github.io/knowledge-base/

plugins:
  - search
  - macros
  - gen-files:
      scripts:
        - generate_papers.py

theme:
  name: material
  logo: icon.png   
  favicon: favicon.png

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  
  font:
    text: Atkinson Hyperlegible Next
    code: Atkinson Hyperlegible Mono

  markdown_extensions:
    - meta
    - admonition
    - footnotes
    - pymdownx.superfences
    - pymdownx.snippets:
        jinja: true
    - attr_list
    - toc:
        permalink: true

  features:
    - navigation.expand
    - navigation.sections
    - content.code.annotate
    - content.tabs.link
    - metadata
    - tags
    - search.highlight

nav:
  - Home: index.md
  - Planning:
    - Path Planning:
      - RRT: papers/1998_lavalle_rapidly_exploring_random_trees.md
    - Trajectory Planning:
      - Kinodynamic RRT: papers/1999_lavalle_randomized_kinodynamic_planning.md
  - Prediction:
    - Real-Time Learning of Predictive Dynamic Obstacle Models for Robotic Motion Planning: papers/2511_00814.md
  - Control:
    - Robust Control:
      - Robustness margins for LQG: papers/1978_doyle_guaranteed_margins_for_lqg.md
  - Machine Learning:
    - Attention Is All You Need: papers/1706_03762.md