"""Source registry for the table-driven prefill runner."""

from __future__ import annotations

from knowledge_base.config import REPO_ROOT
from knowledge_base.utils.prefill_template import SourceSpec


def _input(name: str):
    return REPO_ROOT / "todo" / "papers" / f"{name.upper()}.md"


def _simple_url_source(name: str, hint: str, needle: str) -> SourceSpec:
    return SourceSpec(
        name=name,
        description=f"Prefill metadata from {hint} URLs.",
        default_input=_input(name),
        mode="url_doi",
        entry_kind="URLs",
        source_hint=hint,
        accept_url=lambda url, needle=needle: needle in url,
    )


def source_specs() -> dict[str, SourceSpec]:
    from knowledge_base.scripts.prefill import (
        acm,
        arxiv,
        asme,
        bmva,
        dagstuhl,
        elsevier,
        ieee,
        jmlr,
        jstor,
        mdpi,
        mit_press,
        mlr,
        msp,
        nasa,
        nature,
        neurips,
        nist,
        openreview,
        oup,
        project_euclid,
        rand,
        researchgate,
        rss,
        semantic_scholar,
        springer,
        taylor_francis,
        usenix,
    )

    return {
        source.name: source
        for source in [
            _simple_url_source("annual_reviews", "Annual Reviews", "annualreviews.org/"),
            _simple_url_source("apa", "APA PsycNet", "psycnet.apa.org/"),
            _simple_url_source("imaging_science", "Imaging Science", "library.imaging.org/"),
            _simple_url_source("optica", "Optica", "opg.optica.org/"),
            _simple_url_source("sage", "SAGE", "journals.sagepub.com/"),
            _simple_url_source("science", "Science", "science.org/"),
            _simple_url_source("siam", "SIAM", "epubs.siam.org/"),
            _simple_url_source("wiley", "Wiley", "onlinelibrary.wiley.com/"),
            SourceSpec(
                "acm",
                "Prefill metadata from ACM DL URLs.",
                _input("acm"),
                "doi",
                entry_kind="ACM DL URLs",
                extract_entries=acm.extract_entries,
                entry_label=acm.entry_label,
                entry_doi=acm.entry_doi,
                source_key_for_entry=acm.source_key_for_entry,
                fetch_fields=acm.fetch_fields,
                postprocess_metadata=acm.postprocess_metadata,
            ),
            SourceSpec(
                "arxiv",
                "Prefill arXiv metadata files.",
                _input("arxiv"),
                "custom",
                entry_kind="arXiv IDs",
                delay=0.0,
                fetch_error_label="fetching",
                extract_entries=arxiv.extract_entries,
                source_key_for_entry=arxiv.source_key_for_entry,
                source_key_for_token=arxiv.source_key_for_token,
                existing_for_entry=arxiv.existing_for_entry,
                needs_fetch_for_list_skipped=arxiv.needs_fetch_for_list_skipped,
                prepare_context=arxiv.prepare_context,
                fetch_fields=arxiv.fetch_fields,
                build_metadata=arxiv.build_prefill_metadata,
                write_metadata=arxiv.write_prefill_metadata,
                success_message=arxiv.success_message,
            ),
            SourceSpec(
                "asme",
                "Prefill metadata from ASME Digital Collection URLs.",
                _input("asme"),
                "url_doi",
                entry_kind="URLs",
                source_hint="ASME",
                accept_url=asme.accept_url,
                entry_doi=asme.entry_doi,
            ),
            SourceSpec(
                "bmva",
                "Prefill metadata from BMVA archive PDFs.",
                _input("bmva"),
                "pdf",
                entry_kind="PDF URLs",
                source_hint="BMVA",
                accept_url=bmva.accept_url,
                fields_from_pdf=bmva.fields_from_pdf,
            ),
            SourceSpec(
                "dagstuhl",
                "Prefill metadata from Dagstuhl/LIPIcs URLs.",
                _input("dagstuhl"),
                "doi",
                entry_kind="Dagstuhl DOIs",
                extract_entries=dagstuhl.extract_entries,
                entry_label=dagstuhl.entry_label,
                entry_doi=dagstuhl.entry_doi,
                source_key_for_token=dagstuhl.source_key_for_token,
                postprocess_crossref_data=dagstuhl.postprocess_crossref_data,
                doi_link_alt=True,
            ),
            SourceSpec(
                "elsevier",
                "Prefill metadata from ScienceDirect URLs.",
                _input("elsevier"),
                "doi",
                entry_kind="ScienceDirect PIIs",
                show_resolved_doi=True,
                extract_entries=elsevier.extract_entries,
                entry_label=elsevier.entry_label,
                source_key_for_token=elsevier.source_key_for_token,
                resolve_doi=elsevier.resolve_doi,
            ),
            SourceSpec(
                "ieee",
                "Prefill metadata from IEEE Xplore URLs.",
                _input("ieee"),
                "doi",
                entry_kind="IEEE articles",
                show_resolved_doi=True,
                extract_entries=ieee.extract_entries,
                entry_label=ieee.entry_label,
                source_key_for_token=ieee.source_key_for_token,
                resolve_doi=ieee.resolve_doi,
            ),
            SourceSpec(
                "jmlr",
                "Prefill metadata from JMLR URLs.",
                _input("jmlr"),
                "citation",
                entry_kind="URLs",
                source_fallback="Journal of Machine Learning Research",
                type_fallback="Journal Paper",
                source_hint="JMLR",
                accept_url=jmlr.accept_url,
                normalize_url=jmlr.normalize_url,
            ),
            SourceSpec(
                "jstor",
                "Prefill metadata from JSTOR stable URLs.",
                _input("jstor"),
                "doi",
                entry_kind="JSTOR stable URLs",
                extract_entries=jstor.extract_entries,
                entry_label=jstor.entry_label,
                entry_doi=jstor.entry_doi,
                source_key_for_entry=jstor.source_key_for_entry,
                source_key_for_token=jstor.source_key_for_token,
                postprocess_crossref_data=jstor.postprocess_crossref_data,
                doi_link_alt=True,
            ),
            SourceSpec(
                "mdpi",
                "Prefill metadata from MDPI URLs.",
                _input("mdpi"),
                "url_doi",
                entry_kind="URLs",
                source_hint="MDPI",
                accept_url=mdpi.accept_url,
                entry_doi=mdpi.entry_doi,
            ),
            SourceSpec(
                "mit_press",
                "Prefill metadata from MIT Press Direct URLs.",
                _input("mit_press"),
                "url_doi",
                entry_kind="URLs",
                source_hint="MIT Press",
                accept_url=mit_press.accept_url,
                entry_doi=mit_press.entry_doi,
                postprocess_crossref_data=mit_press.postprocess_crossref_data,
            ),
            SourceSpec(
                "mlr",
                "Prefill metadata from PMLR/MLR URLs.",
                _input("mlr"),
                "page",
                entry_kind="PMLR URLs",
                extract_entries=mlr.extract_entries,
                source_key_for_token=mlr.source_key_for_token,
                fetch_fields=mlr.fetch_fields,
            ),
            SourceSpec(
                "msp",
                "Prefill metadata from MSP URLs.",
                _input("msp"),
                "doi",
                entry_kind="MSP DOIs",
                extract_entries=msp.extract_entries,
                entry_label=msp.entry_label,
                entry_doi=msp.entry_doi,
                source_key_for_token=msp.source_key_for_token,
                postprocess_crossref_data=msp.postprocess_crossref_data,
                doi_link_alt=True,
            ),
            SourceSpec(
                "nasa",
                "Prefill metadata from NASA NTRS URLs.",
                _input("nasa"),
                "page",
                entry_kind="NASA NTRS citations",
                extract_entries=nasa.extract_entries,
                source_key_for_entry=nasa.source_key_for_entry,
                source_key_for_token=nasa.source_key_for_token,
                fetch_fields=nasa.fetch_fields,
            ),
            SourceSpec(
                "nature",
                "Prefill metadata from nature.com URLs.",
                _input("nature"),
                "doi",
                entry_kind="Nature DOIs",
                show_resolved_doi=True,
                extract_entries=nature.extract_entries,
                entry_label=nature.entry_label,
                entry_doi=nature.entry_doi,
                source_key_for_token=nature.source_key_for_token,
                fetch_fields=nature.fetch_fields,
                doi_link_alt=True,
            ),
            SourceSpec(
                "neurips",
                "Prefill metadata from NeurIPS/NIPS URLs.",
                _input("neurips"),
                "page",
                entry_kind="NeurIPS papers",
                extract_entries=neurips.extract_entries,
                entry_label=neurips.entry_label,
                source_key_for_token=neurips.source_key_for_token,
                fetch_fields=neurips.fetch_fields,
            ),
            SourceSpec(
                "nist",
                "Prefill metadata from NIST/NBS PDFs.",
                _input("nist"),
                "pdf",
                entry_kind="PDF URLs",
                source_hint="NIST",
                accept_url=nist.accept_url,
                fields_from_pdf=nist.fields_from_pdf,
            ),
            SourceSpec(
                "openreview",
                "Prefill metadata from OpenReview URLs.",
                _input("openreview"),
                "page",
                entry_kind="OpenReview notes",
                extract_entries=openreview.extract_entries,
                source_key_for_entry=openreview.source_key_for_entry,
                source_key_for_token=openreview.source_key_for_token,
                fetch_fields=openreview.fetch_fields,
            ),
            SourceSpec(
                "oup",
                "Prefill metadata from Oxford Academic URLs.",
                _input("oup"),
                "url_doi",
                entry_kind="URLs",
                source_hint="Oxford Academic",
                accept_url=oup.accept_url,
                entry_doi=oup.entry_doi,
            ),
            SourceSpec(
                "project_euclid",
                "Prefill metadata from Project Euclid URLs.",
                _input("project_euclid"),
                "page",
                entry_kind="Project Euclid URLs",
                extract_entries=project_euclid.extract_entries,
                fetch_fields=project_euclid.fetch_fields,
            ),
            SourceSpec(
                "rand",
                "Prefill metadata from RAND URLs.",
                _input("rand"),
                "citation",
                entry_kind="URLs",
                source_fallback="RAND Corporation",
                type_fallback="Technical Report",
                source_hint="RAND",
                accept_url=rand.accept_url,
            ),
            SourceSpec(
                "researchgate",
                "Prefill metadata from ResearchGate URLs.",
                _input("researchgate"),
                "page",
                entry_kind="ResearchGate URLs",
                extract_entries=researchgate.extract_entries,
                fetch_fields=researchgate.fetch_fields,
            ),
            SourceSpec(
                "rss",
                "Prefill metadata from RSS proceedings URLs.",
                _input("rss"),
                "page",
                entry_kind="RSS papers",
                extract_entries=rss.extract_entries,
                entry_label=rss.entry_label,
                source_key_for_token=rss.source_key_for_token,
                fetch_fields=rss.fetch_fields,
            ),
            SourceSpec(
                "semantic_scholar",
                "Prefill metadata from Semantic Scholar URLs.",
                _input("semantic_scholar"),
                "semantic",
                entry_kind="Semantic Scholar papers",
                source_fallback="Semantic Scholar",
                extract_entries=semantic_scholar.extract_entries,
                source_key_for_entry=lambda entry: entry,
                source_key_for_token=semantic_scholar.source_key_for_token,
                entry_label=semantic_scholar.entry_label,
                build_metadata=semantic_scholar.build_metadata,
            ),
            SourceSpec(
                "springer",
                "Prefill metadata from Springer URLs.",
                _input("springer"),
                "doi",
                entry_kind="DOIs",
                extract_entries=springer.extract_entries,
                entry_label=springer.entry_label,
                entry_doi=springer.entry_doi,
                postprocess_crossref_data=springer.postprocess_crossref_data,
            ),
            SourceSpec(
                "taylor_francis",
                "Prefill metadata from Taylor & Francis URLs.",
                _input("taylor_francis"),
                "doi",
                entry_kind="Taylor & Francis DOIs",
                extract_entries=taylor_francis.extract_entries,
                entry_label=taylor_francis.entry_label,
                entry_doi=taylor_francis.entry_doi,
                postprocess_crossref_data=taylor_francis.postprocess_crossref_data,
                doi_link_alt=True,
            ),
            SourceSpec(
                "usenix",
                "Prefill metadata from USENIX PDFs.",
                _input("usenix"),
                "pdf",
                entry_kind="PDF URLs",
                source_hint="USENIX",
                accept_url=usenix.accept_url,
                fields_from_pdf=usenix.fields_from_pdf,
            ),
        ]
    }
